/*
 * JF_MathExpression.java
 *
 * Created on 20 novembre 2006, 13.30
 */

/**
 *
 * @author  luca
 */
public class JF_MathExpression extends javax.swing.JDialog {

    /** Creates new form JF_MathExpression */
    public JF_MathExpression(MDM_JF_Pivot f_Pivot) 
    {        
        super((java.awt.Frame)f_Pivot,false);     
        
        this.jtable = f_Pivot.getTable_Pivot();
        initComponents();
        
        jp_ExpreParser = new jP_ExpressionParser(f_Pivot,this);
        getContentPane().add(jp_ExpreParser, java.awt.BorderLayout.CENTER);
        
        setCenteredFrame(650,450); 
    }
  
    private void setCenteredFrame(int width,int height)
    {
        java.awt.Toolkit kit = java.awt.Toolkit.getDefaultToolkit();
        java.awt.Dimension screenSize = kit.getScreenSize();        
        int screenWCenter = screenSize.width/2;
        int screenHCenter = screenSize.height/2;        
        this.setSize(width,height);
        this.setLocation(screenWCenter-(width/2),screenHCenter-(height/2));  
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        
        setTitle("N.T.M. functions");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        
        pack();
    }//GEN-END:initComponents

    private void jButtonColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColActionPerformed
 
    }//GEN-LAST:event_jButtonColActionPerformed

    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        close_JF_MathExpression();
    }//GEN-LAST:event_exitForm
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void close_JF_MathExpression()
    {
        javax.swing.table.JTableHeader header = this.jtable.getTableHeader();
        header.setReorderingAllowed(true);
        
        if(jp_ExpreParser != null)
            jp_ExpreParser.stop_TH();
        jp_ExpreParser = null;
        
        dispose();
    }
        
    private jP_ExpressionParser jp_ExpreParser;
    private javax.swing.JTable jtable  = null;
    
}