/*
 * MDM_JP_ProgBar.java
 *
 * Created on 2 dicembre 2004, 14.19
 */

/**
 *
 * @author  root
 */
public class MDM_JP_ProgBar extends javax.swing.JPanel {

    /** Creates new form MDM_JP_ProgBar */
    public MDM_JP_ProgBar() {
        initComponents();
        jProgressBar1.setFont(staticLib.fontA9);
        jL_desc.setFont(staticLib.fontA9);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jL_icon = new javax.swing.JLabel();
        jP_ProgBar = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jL_desc = new javax.swing.JLabel();
        
        setLayout(new java.awt.BorderLayout());
        
        setBackground(new java.awt.Color(230, 230, 230));
        jL_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ledoff.gif")));
        jL_icon.setForeground(java.awt.Color.black);
        jL_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_icon.setPreferredSize(new java.awt.Dimension(21, 25));
        add(jL_icon, java.awt.BorderLayout.NORTH);
        
        jP_ProgBar.setLayout(new java.awt.CardLayout(10, 5));
        
        jP_ProgBar.setBackground(new java.awt.Color(230, 230, 230));
        jProgressBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jProgressBar1.setForeground(java.awt.Color.blue);
        jProgressBar1.setBackground(new java.awt.Color(230, 230, 230));
        jProgressBar1.setStringPainted(true);
        jP_ProgBar.add(jProgressBar1, "jProgressBar1");
        
        add(jP_ProgBar, java.awt.BorderLayout.CENTER);
        
        jL_desc.setForeground(java.awt.Color.black);
        jL_desc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_desc.setPreferredSize(new java.awt.Dimension(10, 18));
        add(jL_desc, java.awt.BorderLayout.SOUTH);
        
    }//GEN-END:initComponents

    
        
    public javax.swing.JProgressBar get_jProgressBar()
    {
        return this.jProgressBar1;
    }
    
    public javax.swing.JLabel get_JLabelDesc()
    {
        return this.jL_desc;
    }
    
    public javax.swing.JLabel get_JLabelIcon()
    {
        return this.jL_icon;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jL_icon;
    private javax.swing.JPanel jP_ProgBar;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel jL_desc;
    // End of variables declaration//GEN-END:variables

}
