/*
 * MDM_JD_Request.java
 *
 * Created on 2012.
 */

/**
 *
 * @author  luca
 */

import javax.swing.table.AbstractTableModel;
import javax.swing.table.*;
import java.awt.Cursor;
import java.util.Vector;
import net.etech.*;
import net.etech.ASP.*;
import net.etech.MDM.*;
import net.etech.loadconfig.*;

public class MDM_JD_Request extends javax.swing.JDialog {

    /** Creates new form MDM_JD_Request */
    public MDM_JD_Request(javax.swing.JFrame parent,STRUCT_PARAMS struct_param,BufferRestrizioni BR_drillDown,getConfigFiltro configuration) 
    {
        super(parent, true);
        this.jFrameParent = parent;
        this.local_struct_param = struct_param;
        
        initComponents();
        
        this.setTitle("Drill-Down Analysis");
        jL_title.setText("Drill-Down Analysis");        
        
        MDM_JP_RestrictionList restriction = new MDM_JP_RestrictionList(BR_drillDown,false,false);
        jP_center.add("Center",restriction);
        
        jp_centrali = new MDM_JP_Centrali(jB_SEND,jP_Bar,jL_status,this.local_struct_param,true);
        jp_centrali.setConfiguration(configuration);
        jP_status_SW.add(jp_centrali,java.awt.BorderLayout.CENTER);
        
        jB_SEND.setCursor(Cur_hand);
        jB_CLOSE.setCursor(Cur_hand);
        
        pack();
    }


    public void show_JD_Request()
    {        
        setCenteredFrame(500,500);
        setVisible(true);
        toFront();
    }
    private void setCenteredFrame(int width,int height)
    {
        java.awt.Toolkit kit = java.awt.Toolkit.getDefaultToolkit();
        java.awt.Dimension screenSize = kit.getScreenSize();        
        int screenWCenter = screenSize.width/2;
        int screenHCenter = screenSize.height/2;        
        this.setSize(width,height);
        this.setLocation(screenWCenter-(width/2),screenHCenter-(height/2));  
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jP_TOT = new javax.swing.JPanel();
        jL_title = new javax.swing.JLabel();
        jP_center = new javax.swing.JPanel();
        jP_south = new javax.swing.JPanel();
        jP_status_TOT = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jP_Bar = new javax.swing.JProgressBar();
        jP_status_SW = new javax.swing.JPanel();
        jL_status = new javax.swing.JLabel();
        jB_SEND = new javax.swing.JButton();
        jB_CLOSE = new javax.swing.JButton();
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        
        jP_TOT.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        
        jP_TOT.setBackground(new java.awt.Color(230, 230, 230));
        jL_title.setFont(new java.awt.Font("Dialog", 1, 16));
        jL_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/drilldown.png")));
        jL_title.setText("Title");
        jL_title.setMinimumSize(new java.awt.Dimension(149, 48));
        jL_title.setPreferredSize(new java.awt.Dimension(150, 48));
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 0;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jP_TOT.add(jL_title, gridBagConstraints1);
        
        jP_center.setLayout(new java.awt.BorderLayout());
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 1;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.weightx = 1.0;
        gridBagConstraints1.weighty = 1.0;
        jP_TOT.add(jP_center, gridBagConstraints1);
        
        jP_south.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints2;
        
        jP_south.setBackground(new java.awt.Color(230, 230, 230));
        jP_south.setMinimumSize(new java.awt.Dimension(181, 150));
        jP_south.setPreferredSize(new java.awt.Dimension(10, 150));
        jP_status_TOT.setLayout(new java.awt.BorderLayout());
        
        jP_status_TOT.setBackground(new java.awt.Color(230, 230, 230));
        jP_status_TOT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 121, 170), 1, true));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Process");
        jLabel5.setMaximumSize(new java.awt.Dimension(65, 18));
        jLabel5.setMinimumSize(new java.awt.Dimension(65, 18));
        jLabel5.setPreferredSize(new java.awt.Dimension(65, 18));
        jP_status_TOT.add(jLabel5, java.awt.BorderLayout.SOUTH);
        
        jPanel4.setLayout(new java.awt.CardLayout(10, 5));
        
        jPanel4.setBackground(new java.awt.Color(230, 230, 230));
        jP_Bar.setBackground(new java.awt.Color(230, 230, 230));
        jP_Bar.setForeground(java.awt.Color.blue);
        jP_Bar.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jP_Bar.setToolTipText("");
        jP_Bar.setStringPainted(true);
        jPanel4.add(jP_Bar, "jProgressBar2");
        
        jP_status_TOT.add(jPanel4, java.awt.BorderLayout.CENTER);
        
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 0;
        gridBagConstraints2.gridy = 0;
        gridBagConstraints2.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints2.insets = new java.awt.Insets(3, 3, 3, 3);
        jP_south.add(jP_status_TOT, gridBagConstraints2);
        
        jP_status_SW.setLayout(new java.awt.BorderLayout());
        
        jP_status_SW.setBackground(new java.awt.Color(230, 230, 230));
        jP_status_SW.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 121, 170), 1, true));
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 1;
        gridBagConstraints2.gridy = 0;
        gridBagConstraints2.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints2.insets = new java.awt.Insets(3, 3, 3, 3);
        gridBagConstraints2.weightx = 1.0;
        gridBagConstraints2.weighty = 1.0;
        jP_south.add(jP_status_SW, gridBagConstraints2);
        
        jL_status.setText(" Status :");
        jL_status.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 121, 170), 1, true));
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 1;
        gridBagConstraints2.gridy = 1;
        gridBagConstraints2.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints2.insets = new java.awt.Insets(3, 3, 3, 3);
        jP_south.add(jL_status, gridBagConstraints2);
        
        jB_SEND.setBackground(new java.awt.Color(230, 230, 230));
        jB_SEND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/send_request.jpg")));
        jB_SEND.setToolTipText("Report Request");
        jB_SEND.setBorderPainted(false);
        jB_SEND.setContentAreaFilled(false);
        jB_SEND.setFocusPainted(false);
        jB_SEND.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jB_SEND.setMaximumSize(new java.awt.Dimension(110, 26));
        jB_SEND.setMinimumSize(new java.awt.Dimension(110, 26));
        jB_SEND.setPreferredSize(new java.awt.Dimension(110, 26));
        jB_SEND.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/send_request_press.jpg")));
        jB_SEND.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/send_request_over.jpg")));
        jB_SEND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_SENDActionPerformed(evt);
            }
        });
        
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 2;
        gridBagConstraints2.gridy = 0;
        gridBagConstraints2.insets = new java.awt.Insets(2, 8, 2, 8);
        jP_south.add(jB_SEND, gridBagConstraints2);
        
        jB_CLOSE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.jpg")));
        jB_CLOSE.setToolTipText("Cancel");
        jB_CLOSE.setBorderPainted(false);
        jB_CLOSE.setContentAreaFilled(false);
        jB_CLOSE.setFocusPainted(false);
        jB_CLOSE.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jB_CLOSE.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_press.jpg")));
        jB_CLOSE.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_over.jpg")));
        jB_CLOSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_CLOSEActionPerformed(evt);
            }
        });
        
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 2;
        gridBagConstraints2.gridy = 1;
        gridBagConstraints2.insets = new java.awt.Insets(2, 8, 2, 8);
        gridBagConstraints2.anchor = java.awt.GridBagConstraints.EAST;
        jP_south.add(jB_CLOSE, gridBagConstraints2);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 2;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.weightx = 0.7;
        jP_TOT.add(jP_south, gridBagConstraints1);
        
        getContentPane().add(jP_TOT, java.awt.BorderLayout.CENTER);
        
        pack();
    }//GEN-END:initComponents
   
    private void jB_SENDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_SENDActionPerformed
        
                
        boolean BLOCK_ANALISI = false;
        int MAX_SELECTED_DAY = 15; //Massimo di giorni selezionati
        int MIN_RESTRICTION  = 3; //Numero minimo di restrizioni.
        
        // ------------------
        int LENGTH_strSelectedDays = 0;        
        for(int d=0; d<local_struct_param.ElaborationData.length; d++)
        {
            String dateString = new String(local_struct_param.ElaborationData[d].dateString).trim();
            if(dateString.length() > 0)
            {
                //System.out.println("dateString["+d+"] --> "+dateString);
                LENGTH_strSelectedDays++;
            }
        }
        
        if(LENGTH_strSelectedDays > MAX_SELECTED_DAY)
        {
           if( local_struct_param.Filters.length < MIN_RESTRICTION )           
               BLOCK_ANALISI = true;              
        }
        if(BLOCK_ANALISI == true)
        {   
            String msg_BLOCK_ANALISI =  "Analysis greater than "+MAX_SELECTED_DAY+" days allowed only for "+MIN_RESTRICTION+" or more restrictions.";
            staticLib.optionPanel(msg_BLOCK_ANALISI,"Information",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        // ------------------
        
        if(!jp_centrali.isAlive())
        {
            jp_centrali.startElaboration(2);
            jB_SEND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stop_request.jpg")));
            jB_SEND.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stop_request_over.jpg")));
            jB_SEND.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stop_request_press.jpg")));
            jB_SEND.setToolTipText(" Stop Request ");
        }
        else
        {
                int risp1 = staticLib.confirmPanel("Confirm request ?","Information",javax.swing.JOptionPane.YES_NO_OPTION,javax.swing.JOptionPane.INFORMATION_MESSAGE); 
                if(risp1 == 0)
                { 
                    jB_SEND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/send_request.jpg")));
                    jB_SEND.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/send_request_over.jpg")));
                    jB_SEND.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/send_request_press.jpg")));
                    jB_SEND.setToolTipText(" Send Request ");                    
                    jp_centrali.stopElaboration(); 
                }
        }
    }//GEN-LAST:event_jB_SENDActionPerformed

      
    private void jB_CLOSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_CLOSEActionPerformed
         close_Dialog();
    }//GEN-LAST:event_jB_CLOSEActionPerformed

    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
       close_Dialog();
    }//GEN-LAST:event_closeDialog
    private void close_Dialog()
    {
        if(jp_centrali.isAlive())
        {
            int risp1 = staticLib.confirmPanel("Confirm request ?","Information",javax.swing.JOptionPane.YES_NO_OPTION,javax.swing.JOptionPane.INFORMATION_MESSAGE); 
                if(risp1 == 0)
                { 
                    jB_SEND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/send_request.jpg")));
                    jB_SEND.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/send_request_over.jpg")));
                    jB_SEND.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/send_request_press.jpg")));
                    jB_SEND.setToolTipText(" Send Request ");                    
                    jp_centrali.stopElaboration(); 
                }
        }
        //System.out.println("height = "+this.getSize().height+" width = "+this.getSize().width);
        setVisible(false);
        dispose();
        
        jFrameParent.toFront();
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jP_TOT;
    private javax.swing.JLabel jL_title;
    private javax.swing.JPanel jP_center;
    private javax.swing.JPanel jP_south;
    private javax.swing.JPanel jP_status_TOT;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jP_Bar;
    private javax.swing.JPanel jP_status_SW;
    private javax.swing.JLabel jL_status;
    private javax.swing.JButton jB_SEND;
    private javax.swing.JButton jB_CLOSE;
    // End of variables declaration//GEN-END:variables

    private Cursor Cur_default  = new Cursor(Cursor.DEFAULT_CURSOR);
    private Cursor Cur_wait     = new Cursor(Cursor.WAIT_CURSOR);
    private Cursor Cur_hand     = new Cursor(Cursor.HAND_CURSOR);
    
    private MDM_JP_Centrali jp_centrali;
    private javax.swing.JFrame jFrameParent;
    private STRUCT_PARAMS local_struct_param = null;
}


