ALTER TABLE OPS$ORBIX.TAB_ALARM_RELATION
 DROP PRIMARY KEY CASCADE;
DROP TABLE OPS$ORBIX.TAB_ALARM_RELATION CASCADE CONSTRAINTS;

CREATE TABLE OPS$ORBIX.TAB_ALARM_RELATION
(
  ID_ALARM_RELATION         VARCHAR2(30 BYTE)   NOT NULL,
  DESCRIPTION               VARCHAR2(256 BYTE),
  ID_CONDITION_SCRIPT       NUMBER(6),
  STR_CONDITION_PLUGIN      VARCHAR2(30 BYTE),
  TIPO_DI_CONFIGURAZIONE    VARCHAR2(30 BYTE)   NOT NULL,
  COUNTERS_KIT_ID           NUMBER(6)           NOT NULL,
  TIME_FRACTION_ELEMENT_ID  NUMBER(6)           NOT NULL,
  FAMILY_ID                 NUMBER(6)
)
TABLESPACE TBS_RETE7
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             160K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OPS$ORBIX.TABLE1_PK ON OPS$ORBIX.TAB_ALARM_RELATION
(ID_ALARM_RELATION, TIPO_DI_CONFIGURAZIONE)
NOLOGGING
TABLESPACE TBS_RETE7
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             160K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX OPS$ORBIX.TAB_ALARM_RELATION_UK1 ON OPS$ORBIX.TAB_ALARM_RELATION
(ID_ALARM_RELATION)
NOLOGGING
TABLESPACE TBS_RETE7
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             160K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE OPS$ORBIX.TAB_ALARM_RELATION ADD (
  CONSTRAINT TABLE1_PK
 PRIMARY KEY
 (ID_ALARM_RELATION, TIPO_DI_CONFIGURAZIONE)
    USING INDEX 
    TABLESPACE TBS_RETE7
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          160K
                NEXT             160K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ),
  CONSTRAINT TAB_ALARM_RELATION_UK1
 UNIQUE (ID_ALARM_RELATION)
    USING INDEX 
    TABLESPACE TBS_RETE7
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          160K
                NEXT             160K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
