ALTER TABLE OPS$ORBIX.TAB_ALARM_THRESHOLD_GENERATOR
 DROP PRIMARY KEY CASCADE;
DROP TABLE OPS$ORBIX.TAB_ALARM_THRESHOLD_GENERATOR CASCADE CONSTRAINTS;

CREATE TABLE OPS$ORBIX.TAB_ALARM_THRESHOLD_GENERATOR
(
  ID_THRESHOLD_GENERATOR    NUMBER(6)           NOT NULL,
  DESCRIPTION               VARCHAR2(256 BYTE)  NOT NULL,
  TYPE_THRESHOLD            NUMBER              NOT NULL,
  ENABLE_HOLYDAY_THRESHOLD  CHAR(1 BYTE),
  STR_PLUGIN                VARCHAR2(30 BYTE)   NOT NULL,
  TIPO_DI_CONFIGURAZIONE    VARCHAR2(30 BYTE)   NOT NULL,
  THRESHOLD_PERSISTENCE     NUMBER(3)           NOT NULL,
  HOURS_AGGREGATE           NUMBER(2)           NOT NULL
)
TABLESPACE TBS_RETE7
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             160K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OPS$ORBIX.TAB_ALARM_THRESHOLD_PK ON OPS$ORBIX.TAB_ALARM_THRESHOLD_GENERATOR
(ID_THRESHOLD_GENERATOR)
NOLOGGING
TABLESPACE TBS_RETE7
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             160K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE OPS$ORBIX.TAB_ALARM_THRESHOLD_GENERATOR ADD (
  CONSTRAINT TAB_ALARM_THRESHOLD_PK
 PRIMARY KEY
 (ID_THRESHOLD_GENERATOR)
    USING INDEX 
    TABLESPACE TBS_RETE7
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          160K
                NEXT             160K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
