DROP TABLE OPS$ORBIX.TAB_ALARM_SERVER_MASTER CASCADE CONSTRAINTS;

CREATE TABLE OPS$ORBIX.TAB_ALARM_SERVER_MASTER
(
  TIPO_DI_CONFIGURAZIONE  VARCHAR2(30 BYTE)     NOT NULL,
  ID_ALARM_RELATION       NUMBER(6)             NOT NULL,
  SERVER_ID               NUMBER(6)             NOT NULL,
  DESCRIPTION             VARCHAR2(256 BYTE)
)
TABLESPACE TBS_RETE7
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             160K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP PUBLIC SYNONYM TAB_ALARM_SERVER_MASTER;

CREATE PUBLIC SYNONYM TAB_ALARM_SERVER_MASTER FOR OPS$ORBIX.TAB_ALARM_SERVER_MASTER;