ALTER TABLE OPS$ORBIX.TAB_ALARM_GENERATOR
 DROP PRIMARY KEY CASCADE;
DROP TABLE OPS$ORBIX.TAB_ALARM_GENERATOR CASCADE CONSTRAINTS;

CREATE TABLE OPS$ORBIX.TAB_ALARM_GENERATOR
(
  ID_ALARM_GENERATOR      NUMBER(6)             NOT NULL,
  SHORT_DESCRIPTION       VARCHAR2(60 BYTE)     NOT NULL,
  LONG_DESCRIPTION        VARCHAR2(256 BYTE),
  STR_PLUGIN              VARCHAR2(30 BYTE)     NOT NULL,
  THRESHOLD_MANAGEMENT    CHAR(1 BYTE)          NOT NULL,
  TIPO_DI_CONFIGURAZIONE  VARCHAR2(30 BYTE)     NOT NULL
)
TABLESPACE TBS_RETE7
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             160K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OPS$ORBIX.TAB_ALARM_GENERATOR_PK ON OPS$ORBIX.TAB_ALARM_GENERATOR
(ID_ALARM_GENERATOR)
NOLOGGING
TABLESPACE TBS_RETE7
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             160K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP SYNONYM OPS$ORBIX.T_THR_OVERRIDE;

CREATE SYNONYM OPS$ORBIX.T_THR_OVERRIDE FOR OPS$ORBIX.TAB_ALARM_GENERATOR;


ALTER TABLE OPS$ORBIX.TAB_ALARM_GENERATOR ADD (
  CONSTRAINT TAB_ALARM_GENERATOR_PK
 PRIMARY KEY
 (ID_ALARM_GENERATOR)
    USING INDEX 
    TABLESPACE TBS_RETE7
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          160K
                NEXT             160K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));