/*
 * ADAMS_Calendar.java
 *
 * Created on 13 aprile 2007, 14.58
 */

/**
 *
 * @author  luca
 */
public class ADAMS_Calendar extends javax.swing.JDialog {

    /** Creates new form ADAMS_Calendar */
    public ADAMS_Calendar(java.awt.Frame parent, boolean modal,String Title) {
        super(parent, modal);
        initComponents();

        jB_close.setCursor(Cur_hand);
        jB_apply.setVisible(false);
       
        this.setTitle(Title);
        JPCal = new ADAMS_JP_Cal();
        this.add(JPCal,java.awt.BorderLayout.CENTER);
        setCenteredFrame(250,250);
        //this.show();
        this.setVisible(true);
    }

    
    public ADAMS_Calendar(String Title,javax.swing.JTextField jtDD,javax.swing.JTextField jtMM,javax.swing.JTextField jtYY,java.awt.Frame parentFrame) 
    {
        super(parentFrame, true);
        initComponents();
        
        jB_apply.setCursor(Cur_hand);
        jB_close.setCursor(Cur_hand);
        
        this.jt_DD = jtDD;
        this.jt_MM = jtMM;
        this.jt_YY = jtYY;
       
        this.setTitle(Title);
        JPCal = new ADAMS_JP_Cal();
        this.add(JPCal,java.awt.BorderLayout.CENTER);
        setCenteredFrame(250,250);
        //this.show();
        this.setVisible(true);
    }
     
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jB_apply = new javax.swing.JButton();
        jB_close = new javax.swing.JButton();
        
        setBackground(new java.awt.Color(230, 230, 230));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        
        jPanel1.setBackground(new java.awt.Color(230, 230, 230));
        jB_apply.setBackground(new java.awt.Color(230, 230, 230));
        jB_apply.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/apply.jpg")));
        jB_apply.setBorderPainted(false);
        jB_apply.setContentAreaFilled(false);
        jB_apply.setFocusPainted(false);
        jB_apply.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/apply_press.jpg")));
        jB_apply.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/apply_over.jpg")));
        jB_apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_applyActionPerformed(evt);
            }
        });
        
        jPanel1.add(jB_apply);
        
        jB_close.setBackground(new java.awt.Color(230, 230, 230));
        jB_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.jpg")));
        jB_close.setBorderPainted(false);
        jB_close.setContentAreaFilled(false);
        jB_close.setFocusPainted(false);
        jB_close.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_press.jpg")));
        jB_close.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_over.jpg")));
        jB_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_closeActionPerformed(evt);
            }
        });
        
        jPanel1.add(jB_close);
        
        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);
        
        pack();
    }//GEN-END:initComponents
    
    private void jB_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_closeActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jB_closeActionPerformed

    private void jB_applyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_applyActionPerformed
        /* System.out.println("Day "+JPCal.getDay());
        System.out.println("Month "+JPCal.getMonth());        
        System.out.println("Year "+JPCal.getYear());*/

        if( jt_DD != null)
        {   
            String zero = "";
            String strDay = new String(""+JPCal.getDay());
            if((strDay.length() == 1))
                zero ="0";
            
            this.jt_DD.setText(""+zero+strDay);
        }
        if( jt_MM != null)
        {
            String zero1 = "";
            String strMM = new String(""+JPCal.getMonth());
            if((strMM.length() == 1))
                zero1 ="0";
            
            this.jt_MM.setText(""+zero1+strMM);
        }
        if( jt_YY != null)
            this.jt_YY.setText(""+JPCal.getYear());
    }//GEN-LAST:event_jB_applyActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void setCenteredFrame(int width,int height)
    {
        java.awt.Toolkit kit = java.awt.Toolkit.getDefaultToolkit();
        java.awt.Dimension screenSize = kit.getScreenSize();        
        int screenWCenter = screenSize.width/2;
        int screenHCenter = screenSize.height/2;
        
        this.setSize(width,height);
        this.setLocation(screenWCenter-(width/2),screenHCenter-(height/2));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jB_apply;
    private javax.swing.JButton jB_close;
    // End of variables declaration//GEN-END:variables
    private ADAMS_JP_Cal JPCal;
    private javax.swing.JTextField jt_DD;
    private javax.swing.JTextField jt_MM;
    private javax.swing.JTextField jt_YY;
    private java.awt.Cursor Cur_hand     = new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR);
}
