/*
 * ADAMS_JP_Script_p4.java
 *
 * Created on 24 ottobre 2005, 15.34
 */

/**
 *
 * @author  Raffo raffaele.ficcadenti@e-tech.net
 */
import java.awt.Cursor;
import java.util.Vector;

public class ADAMS_JP_Script_p4 extends javax.swing.JPanel {

    private ADAMS_JF_WIZARDBASE                      parent                      = null;
    private Cursor                                  Cur_default                 = new Cursor(Cursor.DEFAULT_CURSOR);
    private Cursor                                  Cur_wait                    = new Cursor(Cursor.WAIT_CURSOR);
    private Cursor                                  Cur_hand                    = new Cursor(Cursor.HAND_CURSOR);
    private VectorHelp                              V_ResultType                = null;
    /** Creates new form ADAMS_JP_Script_p4 */
    public ADAMS_JP_Script_p4(ADAMS_JF_WIZARDBASE parent) {
        this.parent=parent;
        initComponents();
        jL_1.setText("<html><center><b>If you have to assign a "
                        +"<b><font color=#0000ff>name </font>"
                        +"for a variable containing the"
                        +"<b><font color=#0000ff>result </font>"
                        +"of your script. "
                        +"<b><font color=#0000ff>Every script in NTM architecture </font>"
                        +"<b><font color=#ff0000>MUST </font>"
                        +"<b><font color=#0000ff>return a unique well identified result. </font>"
                        +"Such a result have to be placed in a variable called reuslt_variable. The value of the reuslt_variable will be copied in the item the script should handle, so this variable will be treated as of a type compatible with the corresponding item."
                        +"</b><br>");
        jL_4.setText("<html><center><b>If you don't want to assign a name to reuslt_variable, a defoult one will be assigned. The name is diplayed in the line edit below."
                        +"</b><br>");
        jL_5.setText("<html><center><b>"
                        +"<b><font color=#0000ff>Remember </font>"
                        +"That in every case the script result will be serched in the variable shown below. "
                        +"</b><br>");
        //jC_1.addItem("<None>");
        V_ResultType = new VectorHelp(ADAMS_GlobalParam.ALL_CONF_forhelp,ADAMS_GlobalParam.TYPE_RESULT_SCTRIPT);
        Vector AllDesc = V_ResultType.vgetDesc();
        for(int i=0;i<AllDesc.size();i++)
        {
            jC_1.addItem((String)AllDesc.elementAt(i));
        }
        setFont();
        setCursorWidget();
    }
    
    public void setInterface(ScriptObject scriptObject)
    {
                jT_1.setText(scriptObject.sc.RESULTVARNAME);
                String str=V_ResultType.getDescDalValue(scriptObject.sc.RESULTTYPE);
                if(str==null)
                {
                    //jC_1.setSelectedItem("<None>");
                }else
                {
                    jC_1.setSelectedItem((String)str);
                }
    }
    
    public void refreshPanel()
    {
        if(jT_1.getText().equals(""))
        {
            parent.nextButtonSetEnabled(false);
        }else
        {
            parent.nextButtonSetEnabled(true);
        }   
    }
    
    public String getResult()
    {
        return jT_1.getText();
    }
    
    public int getIDType()
    {
        return V_ResultType.getValue((String)jC_1.getSelectedItem());
    }
    
    public void setFont()
    {
    }
    
    public void setCursorWidget()
    {
        jC_1.setCursor(Cur_hand);
        jT_1.setCursor(Cur_hand);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jL_1 = new javax.swing.JLabel();
        jL_4 = new javax.swing.JLabel();
        jT_1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jC_1 = new javax.swing.JComboBox();
        jL_5 = new javax.swing.JLabel();
        
        setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        
        setBackground(new java.awt.Color(230, 230, 230));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jL_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_1.setText("jLabel1");
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.insets = new java.awt.Insets(5, 5, 5, 5);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints1.weightx = 1.0;
        add(jL_1, gridBagConstraints1);
        
        jL_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_4.setText("jLabel4");
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 2;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.insets = new java.awt.Insets(5, 5, 5, 5);
        gridBagConstraints1.weightx = 1.0;
        add(jL_4, gridBagConstraints1);
        
        jT_1.setText("RESULT");
        jT_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jT_1KeyReleased(evt);
            }
        });
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 4;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.insets = new java.awt.Insets(5, 5, 5, 5);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints1.weightx = 1.0;
        add(jT_1, gridBagConstraints1);
        
        jPanel1.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints2;
        
        jPanel1.setBackground(new java.awt.Color(230, 230, 230));
        jPanel1.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(), "The type needed this time is: "));
        jC_1.setBackground(new java.awt.Color(230, 230, 230));
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints2.insets = new java.awt.Insets(10, 10, 10, 10);
        gridBagConstraints2.weightx = 1.0;
        jPanel1.add(jC_1, gridBagConstraints2);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 1;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.insets = new java.awt.Insets(5, 5, 5, 5);
        gridBagConstraints1.weightx = 1.0;
        gridBagConstraints1.weighty = 1.0;
        add(jPanel1, gridBagConstraints1);
        
        jL_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_5.setText("jLabel5");
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 3;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.insets = new java.awt.Insets(5, 5, 5, 5);
        gridBagConstraints1.weightx = 1.0;
        add(jL_5, gridBagConstraints1);
        
    }//GEN-END:initComponents

    private void jT_1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_1KeyReleased
        // Add your handling code here:
        //System.out.println("text="+jT_1.getText());
        if(jT_1.getText().equals(""))
        {
            parent.nextButtonSetEnabled(false);
        }else
        {
            parent.nextButtonSetEnabled(true);
        }
    }//GEN-LAST:event_jT_1KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jL_1;
    private javax.swing.JLabel jL_4;
    private javax.swing.JTextField jT_1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox jC_1;
    private javax.swing.JLabel jL_5;
    // End of variables declaration//GEN-END:variables

}
