/*
 * ADAMS_JF_HelpBasic.java
 *
 * Created on 24 ottobre 2005, 16.49
 */

/**
 *
 * @author  Raffo raffaele.ficcadenti@e-tech.net
 */

import java.awt.Toolkit;
import java.awt.Dimension;
import java.awt.Cursor;
import javax.swing.*; 
import javax.swing.event.*; 
import javax.swing.text.*; 
import javax.swing.text.html.*; 
import javax.swing.border.*; 
import javax.swing.colorchooser.*; 
import javax.swing.filechooser.*; 
import javax.accessibility.*; 
import java.awt.*; 
import java.awt.event.*; 
import java.beans.*; 
import java.util.*; 
import java.io.*; 
import java.applet.*; 
import java.net.*; 


public class ADAMS_JF_HelpBasic extends javax.swing.JDialog {

    private String                                  strURL                      = "";
    private Cursor                                  Cur_default                 = new Cursor(Cursor.DEFAULT_CURSOR);
    private Cursor                                  Cur_wait                    = new Cursor(Cursor.WAIT_CURSOR);
    private Cursor                                  Cur_hand                    = new Cursor(Cursor.HAND_CURSOR);
    
    /** Creates new form ADAMS_JF_HelpBasic */
    
    public ADAMS_JF_HelpBasic(boolean modal,String strURL) 
    {
        super((java.awt.Dialog)ADAMS_GlobalParam.JFRAME_SCRIPT,modal);
        initComponents();
        
        
        vista.setContentType("text/html");
        vista.setEditable(false);
        
        javax.swing.text.html.HTMLEditorKit he = new javax.swing.text.html.HTMLEditorKit();
        vista.setEditorKit(he);
        
        try{
          URL newURL = new URL(strURL);
          setURL(newURL);
        }
        catch (MalformedURLException mue){
          System.out.println("L' URL inserito non è corretto:"+mue);
        }
     
        setTitle(strURL);
        setCenteredFrame(1080,700);
        this.getContentPane().setBackground(new java.awt.Color(230, 230, 230));
        
        setCursorWidget();
        
        //show();
        this.setVisible(true);
    }
    
    public void setCursorWidget()
    {
        jB_close.setCursor(Cur_hand);
    }

    public void setURL(URL newURL)
    {
        try{
            vista.setPage(newURL);
        }catch (IOException ioe){
            System.out.println("Error :"+ioe);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jSp_1 = new javax.swing.JScrollPane();
        vista = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        jB_close = new javax.swing.JButton();
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        
        vista.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
            public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {
                vistaHyperlinkUpdate(evt);
            }
        });
        
        jSp_1.setViewportView(vista);
        
        getContentPane().add(jSp_1, java.awt.BorderLayout.CENTER);
        
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        
        jPanel1.setBackground(new java.awt.Color(230, 230, 230));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.jpg")));
        jB_close.setBorderPainted(false);
        jB_close.setContentAreaFilled(false);
        jB_close.setFocusPainted(false);
        jB_close.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jB_close.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_press.jpg")));
        jB_close.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_over.jpg")));
        jB_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_closeActionPerformed(evt);
            }
        });
        
        jPanel1.add(jB_close);
        
        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);
        
        pack();
    }//GEN-END:initComponents

    private void jB_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_closeActionPerformed
        // Add your handling code here:
        closeFrame();
    }//GEN-LAST:event_jB_closeActionPerformed

    private void vistaHyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {//GEN-FIRST:event_vistaHyperlinkUpdate
        // Add your handling code here:
        if (evt.getEventType() == HyperlinkEvent.EventType.ACTIVATED) { 
 		    if (evt instanceof HTMLFrameHyperlinkEvent) { 
 			((HTMLDocument)vista.getDocument()).processHTMLFrameHyperlinkEvent( 
 			    (HTMLFrameHyperlinkEvent)evt); 
 		    } else { 
 			try { 
 			    setURL(evt.getURL());
 			} catch (Exception ioe) { 
 			    System.out.println("IOE: " + ioe); 
 			} 
 		    } 
 		} 
    }//GEN-LAST:event_vistaHyperlinkUpdate

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        closeFrame();
    }//GEN-LAST:event_closeDialog

    private void setCenteredFrame(int width,int height)
    {
        java.awt.Toolkit kit = Toolkit.getDefaultToolkit();
        Dimension screenSize = kit.getScreenSize();
        int screenWCenter = screenSize.width/2;
        int screenHCenter = screenSize.height/2;

        this.setSize(width,height);
        this.setLocation(screenWCenter-(width/2),screenHCenter-(height/2));
    }
    
    public void closeFrame()
    {
        dispose();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jSp_1;
    private javax.swing.JEditorPane vista;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jB_close;
    // End of variables declaration//GEN-END:variables

}
