/*
 * ADAMS_JP_Script_p6.java
 *
 * Created on 25 ottobre 2005, 11.28
 */

/**
 *
 * @author  Raffo raffaele.ficcadenti@e-tech.net
 */
import java.awt.Cursor;
import java.util.Vector;

public class ADAMS_JP_Script_p6 extends javax.swing.JPanel {

    private Cursor                                  Cur_default                 = new Cursor(Cursor.DEFAULT_CURSOR);
    private Cursor                                  Cur_wait                    = new Cursor(Cursor.WAIT_CURSOR);
    private Cursor                                  Cur_hand                    = new Cursor(Cursor.HAND_CURSOR);
    private ADAMS_JF_WIZARDBASE                      parent                      = null;
    private boolean                                 flagOK                      = false;
    private int                                     flagReport                  = -1;
    /** Creates new form ADAMS_JP_Script_p6 */
    public ADAMS_JP_Script_p6(int flag,ADAMS_JF_WIZARDBASE parent) {
        this.parent=parent;
        flagReport=flag;
        initComponents();
        
        jL_1.setText("<html><center><b><b><font color=#ff0000>Congratulation! </font>"
                        +"Script definition is complete "
                        +"</b><br>");
        jL_2.setText("<html><center><b><b><font color=#0000ff>Now you can try it! </font>"
                        +"Script definition is complete "
                        +"</b><br>");
        jL_3.setText("<html><center><b>Simply assign a value to the external variables substituiting the default ones and press "
                        +"<b><font color=#ffff00>[Try] </font>"
                        +"button "
                        +"</b><br>");
        jL_4.setText("<html><center><b>- or - "
                        +"</b><br>");
        jL_5.setText("<html><center><b>Press the "
                        +"<b><font color=#ffff00>[Commit] </font>"
                        +"button to end the wizard. "
                        +"</b><br>");
        
        vista2.setEditable(false);
        setFont();
        setCursorWidget();
    }
    
    public void refreshPanel()
    {
        boolean flagR=false;
        vista1.setText("");
        Vector appoV=parent.jP_Container_p3.getV1();
        for(int i=0;i<appoV.size();i++)
        {   
            flagR=true;
            ADAMS_JP_Script_p3.vectorTab eleme=(ADAMS_JP_Script_p3.vectorTab)appoV.elementAt(i);
            if(i==0)
                vista1.setText(eleme.st1+" =0");
            else
                vista1.setText(vista1.getText()+"\n"+eleme.st1+" =0");
        }
        
        appoV=parent.jP_Container_p3.getV3();
        for(int i=0;i<appoV.size();i++)
        {   
            ADAMS_JP_Script_p3.vectorTab eleme=(ADAMS_JP_Script_p3.vectorTab)appoV.elementAt(i);
            if((i==0)&&(flagR==false))
                vista1.setText(eleme.st1+" =0");
            else
                vista1.setText(vista1.getText()+"\n"+eleme.st1+" =0");
        }
        
        parent.commitButtonSetEnabled(false);   
    }
    
    public void setFont()
    {
    }
    
    public void setCursorWidget()
    {
        jB_1.setCursor(Cur_hand);
        vista1.setCursor(Cur_hand);
        vista2.setCursor(Cur_hand);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jL_1 = new javax.swing.JLabel();
        jL_2 = new javax.swing.JLabel();
        jL_3 = new javax.swing.JLabel();
        jL_4 = new javax.swing.JLabel();
        jL_5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vista1 = new javax.swing.JEditorPane();
        jPanel2 = new javax.swing.JPanel();
        jB_1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        vista2 = new javax.swing.JEditorPane();
        
        setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        
        setBackground(new java.awt.Color(230, 230, 230));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jL_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_1.setText("jLabel1");
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(5, 5, 5, 5);
        gridBagConstraints1.weightx = 1.0;
        add(jL_1, gridBagConstraints1);
        
        jL_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_2.setText("jLabel2");
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 1;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(5, 5, 5, 5);
        gridBagConstraints1.weightx = 1.0;
        add(jL_2, gridBagConstraints1);
        
        jL_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_3.setText("jLabel3");
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 2;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(5, 5, 5, 5);
        gridBagConstraints1.weightx = 1.0;
        add(jL_3, gridBagConstraints1);
        
        jL_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_4.setText("jLabel4");
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 3;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(5, 5, 5, 5);
        gridBagConstraints1.weightx = 1.0;
        add(jL_4, gridBagConstraints1);
        
        jL_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_5.setText("jLabel5");
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 4;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(5, 5, 5, 5);
        gridBagConstraints1.weightx = 1.0;
        add(jL_5, gridBagConstraints1);
        
        jPanel1.setLayout(new java.awt.BorderLayout());
        
        jPanel1.setBorder(new javax.swing.border.EtchedBorder());
        jScrollPane1.setViewportView(vista1);
        
        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 5;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.insets = new java.awt.Insets(5, 5, 5, 5);
        gridBagConstraints1.weightx = 1.0;
        gridBagConstraints1.weighty = 2.0;
        add(jPanel1, gridBagConstraints1);
        
        jPanel2.setBackground(new java.awt.Color(230, 230, 230));
        jB_1.setBackground(new java.awt.Color(230, 230, 230));
        jB_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exec.png")));
        jB_1.setToolTipText("Add an item to selection");
        jB_1.setFocusPainted(false);
        jB_1.setMaximumSize(new java.awt.Dimension(32767, 32767));
        jB_1.setMinimumSize(new java.awt.Dimension(56, 36));
        jB_1.setPreferredSize(new java.awt.Dimension(56, 36));
        jB_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_1ActionPerformed(evt);
            }
        });
        
        jPanel2.add(jB_1);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 6;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.insets = new java.awt.Insets(5, 5, 5, 5);
        gridBagConstraints1.weightx = 1.0;
        add(jPanel2, gridBagConstraints1);
        
        jPanel3.setLayout(new java.awt.BorderLayout());
        
        jPanel3.setBorder(new javax.swing.border.EtchedBorder());
        jScrollPane2.setViewportView(vista2);
        
        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 7;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.insets = new java.awt.Insets(5, 5, 5, 5);
        gridBagConstraints1.weightx = 1.0;
        gridBagConstraints1.weighty = 2.0;
        add(jPanel3, gridBagConstraints1);
        
    }//GEN-END:initComponents

    private void jB_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_1ActionPerformed
        // Add your handling code here:
        
        flagOK=parent.verifyScript();
        
        //flagOK=true; //commit disabilitata per i report
        if(flagOK==true)
        {
            //vista2.setText("Script OK.");
            parent.commitButtonSetEnabled(flagOK);
            ADAMS_GlobalParam.setLAST_MODIFICATION_TIME(parent.config_NAME_ALIAS);
            if(parent.flagREPORT==ADAMS_GlobalParam.SCRIPT_TE)
            {
                parent.flagCOMMITREPORT=false;
            }
            else if(parent.flagREPORT==ADAMS_GlobalParam.SCRIPT_REPORT)
            {
                parent.flagCOMMITREPORT=true;
            }
        }else
        {
            //vista2.setText("Errore nello script");
            parent.flagCOMMITREPORT=false;
        }
    }//GEN-LAST:event_jB_1ActionPerformed

    public String getTextVar()
    {
        return vista1.getText();
    }
    
    public void setTextVerify(String str)
    {
        vista2.setText(str);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jL_1;
    private javax.swing.JLabel jL_2;
    private javax.swing.JLabel jL_3;
    private javax.swing.JLabel jL_4;
    private javax.swing.JLabel jL_5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JEditorPane vista1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jB_1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JEditorPane vista2;
    // End of variables declaration//GEN-END:variables

}
