/*
 * ADAMS_JP_Report_b1.java
 *
 * Created on 10 agosto 2005, 10.44
 */

/**
 *
 * @author  Raffaele Ficcadenti
 */


import java.awt.Toolkit;
import java.awt.Dimension;
import java.awt.Cursor;
import javax.swing.table.*;
import javax.swing.DefaultCellEditor;
import java.util.Vector;
import java.sql.*;

public class ADAMS_JP_Report_b1 extends javax.swing.JPanel {
    
    private boolean                                 DEBUG                       = false;
    private Cursor                                  Cur_default                 = new Cursor(Cursor.DEFAULT_CURSOR);
    private Cursor                                  Cur_wait                    = new Cursor(Cursor.WAIT_CURSOR);
    private Cursor                                  Cur_hand                    = new Cursor(Cursor.HAND_CURSOR);
    private ADAMS_JP_ReportSchema                    reportSchema                = null;
    private ADAMS_JF_Report                          frame_parent                = null;
    private ADAMS_JD_ReportClone                     jd_cloneReport              = null;
    private boolean                                 enableCommit                = false;
    
    /** Creates new form ADAMS_JP_Report_b1 */
    public ADAMS_JP_Report_b1(ADAMS_JF_Report f,javax.swing.JPanel p) {
        reportSchema=(ADAMS_JP_ReportSchema)p;
        frame_parent=f;
        initComponents();
        setFont();
        setCursorWidget();
    }
    
    public void disableButton(boolean flag)
    {
        //jB_clone.setEnabled(flag);
        //jB_remove.setEnabled(flag);
        //jB_commit.setEnabled(flag);
    }
    
    public javax.swing.JTextArea getAreaHelp()
    {
        return jTextArea1;
    }

    
    public void setFont()
    {
        jTextArea1.setFont(ADAMS_GlobalParam.font_B11);
        
    }
    
    public void setCursorWidget()
    {    
        jB_clone.setCursor(Cur_hand);
        jB_remove.setCursor(Cur_hand);
        jB_commit.setCursor(Cur_hand);
        jB_close.setCursor(Cur_hand);
    }
    
    public void enableCommit(boolean flag)
    {
        if(enableCommit==false)
        {
            enableCommit=frame_parent.testModify3();
            jB_commit.setEnabled(enableCommit);
        }
    }
    
    public void enableCommit()
    {
        enableCommit=true;
        jB_commit.setEnabled(true);
    }
    
    public void disableCommit()
    {
        enableCommit=false;
        jB_commit.setEnabled(false);
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jB_clone = new javax.swing.JButton();
        jB_remove = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jB_commit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jB_close = new javax.swing.JButton();
        
        setLayout(new java.awt.BorderLayout());
        
        setMaximumSize(new java.awt.Dimension(1000, 120));
        setMinimumSize(new java.awt.Dimension(1000, 120));
        setPreferredSize(new java.awt.Dimension(1000, 120));
        jPanel2.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        
        jPanel2.setBackground(new java.awt.Color(230, 230, 230));
        jPanel2.setMinimumSize(new java.awt.Dimension(600, 50));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 50));
        jPanel3.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints2;
        
        jPanel3.setBackground(new java.awt.Color(230, 230, 230));
        jPanel3.setBorder(new javax.swing.border.TitledBorder("Help"));
        jPanel3.setMinimumSize(new java.awt.Dimension(1000, 40));
        jPanel3.setPreferredSize(new java.awt.Dimension(1000, 40));
        jTextArea1.setEditable(false);
        jTextArea1.setLineWrap(true);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints2.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints2.weightx = 1.0;
        gridBagConstraints2.weighty = 1.0;
        jPanel3.add(jTextArea1, gridBagConstraints2);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 1;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints1.weightx = 1.0;
        gridBagConstraints1.weighty = 1.0;
        jPanel2.add(jPanel3, gridBagConstraints1);
        
        jPanel4.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints3;
        
        jPanel4.setBackground(new java.awt.Color(230, 230, 230));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jPanel5.setBackground(new java.awt.Color(230, 230, 230));
        jB_clone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b_clone.jpg")));
        jB_clone.setToolTipText("Cancel");
        jB_clone.setBorderPainted(false);
        jB_clone.setContentAreaFilled(false);
        jB_clone.setFocusPainted(false);
        jB_clone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jB_clone.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jB_clone.setMaximumSize(new java.awt.Dimension(0, 0));
        jB_clone.setMinimumSize(new java.awt.Dimension(56, 30));
        jB_clone.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b_clone_press.jpg")));
        jB_clone.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b_clone_over.jpg")));
        jB_clone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cloneActionPerformed(evt);
            }
        });
        
        jPanel5.add(jB_clone);
        
        jB_remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_schema1.jpg")));
        jB_remove.setToolTipText("Cancel");
        jB_remove.setBorderPainted(false);
        jB_remove.setContentAreaFilled(false);
        jB_remove.setFocusPainted(false);
        jB_remove.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jB_remove.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jB_remove.setMaximumSize(new java.awt.Dimension(0, 0));
        jB_remove.setMinimumSize(new java.awt.Dimension(56, 30));
        jB_remove.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_schema3.jpg")));
        jB_remove.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_schema2.jpg")));
        jB_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cloneActionPerformed(evt);
            }
        });
        
        jPanel5.add(jB_remove);
        
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints3.weightx = 1.0;
        jPanel4.add(jPanel5, gridBagConstraints3);
        
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        
        jPanel6.setBackground(new java.awt.Color(230, 230, 230));
        jB_commit.setBackground(new java.awt.Color(230, 230, 230));
        jB_commit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b_commit.jpg")));
        jB_commit.setBorderPainted(false);
        jB_commit.setContentAreaFilled(false);
        jB_commit.setFocusPainted(false);
        jB_commit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jB_commit.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jB_commit.setMaximumSize(new java.awt.Dimension(32768, 32768));
        jB_commit.setMinimumSize(new java.awt.Dimension(80, 30));
        jB_commit.setPreferredSize(new java.awt.Dimension(80, 30));
        jB_commit.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b_commit_press.jpg")));
        jB_commit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b_commit_over.jpg")));
        jB_commit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cloneActionPerformed(evt);
            }
        });
        
        jPanel6.add(jB_commit);
        
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints3.weightx = 1.0;
        jPanel4.add(jPanel6, gridBagConstraints3);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 0;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        jPanel2.add(jPanel4, gridBagConstraints1);
        
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        
        jPanel1.setBackground(new java.awt.Color(230, 230, 230));
        jB_close.setForeground(java.awt.Color.red);
        jB_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.jpg")));
        jB_close.setBorderPainted(false);
        jB_close.setContentAreaFilled(false);
        jB_close.setFocusPainted(false);
        jB_close.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jB_close.setMaximumSize(new java.awt.Dimension(55, 20));
        jB_close.setMinimumSize(new java.awt.Dimension(55, 20));
        jB_close.setPreferredSize(new java.awt.Dimension(55, 20));
        jB_close.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_press.jpg")));
        jB_close.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_over.jpg")));
        jB_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cloneActionPerformed(evt);
            }
        });
        
        jPanel1.add(jB_close);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 2;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(jPanel1, gridBagConstraints1);
        
        add(jPanel2, java.awt.BorderLayout.CENTER);
        
    }//GEN-END:initComponents

    private void jB_cloneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cloneActionPerformed
        // Add your handling code here:
        if (evt.getSource() == jB_close) 
        {
            frame_parent.closeFrame(false);
        }
        else if (evt.getSource() == jB_commit)
        {
            if(ADAMS_GlobalParam.ctrl_LOCK_TABLE(false) == false)
            {
                return;
            }
            reportSchema.commit();
        }else if (evt.getSource() == jB_remove)
        {
            if(ADAMS_GlobalParam.ctrl_LOCK_TABLE(false) == false)
            {
                return;
            }
            reportSchema.deleteReport(true);
            disableCommit();
        }else if (evt.getSource() == jB_clone)
        {
            if(ADAMS_GlobalParam.ctrl_LOCK_TABLE(false) == false)
            {
                
                return;
            }
            
            if(reportSchema.canClone())
            {
                boolean flagMODIFY=frame_parent.testModify3();
                if(flagMODIFY==true)
                {
                    ADAMS_JD_Message op = new ADAMS_JD_Message(ADAMS_GlobalParam.ADAMS_JD_Report,true,"Warning: No COMMIT has been done. Do you really want to clone ?","Warning",6);
                    int Yes_No = op.getAnswer();
                    
                    if(Yes_No == 1)
                    {
                        ADAMS_GlobalParam.clonato=false;
                        //fai il clone
                    }else
                    {
                        return;
                    }             

                }
                if(jd_cloneReport==null)
                {
                    jd_cloneReport = new ADAMS_JD_ReportClone(true,reportSchema);
                    
                }
                else
                {
                    jd_cloneReport.closeDialog();
                    jd_cloneReport=null;
                    jd_cloneReport = new ADAMS_JD_ReportClone(true,reportSchema);
                }
                if(ADAMS_GlobalParam.clonato==true)
                {
                    frame_parent.aggiornaListaReport();
                    ADAMS_GlobalParam.clonato=false;
                }
            }
            return;
        }
        
    }//GEN-LAST:event_jB_cloneActionPerformed

    public void enableClone(boolean state)
    {
        jB_clone.setEnabled(state);
    }
    
    public void enableRemove(boolean state)
    {
        jB_remove.setEnabled(state);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton jB_clone;
    private javax.swing.JButton jB_remove;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton jB_commit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jB_close;
    // End of variables declaration//GEN-END:variables

}
