Lista Tabelle.

L_INDEX_LIB
L_LIBRERIA_PLUGIN
TAB_ALARM_GENERATOR
TAB_ALARM_GENERATOR_THRESHOLDS
TAB_ALARM_RELATION
TAB_ALARM_RELATION_ELEMENTS
TAB_ALARM_RELATION_HANDLERS
TAB_ALARM_SERVER_MASTER
TAB_ALARM_SERVER_PRODUCTION
TAB_ALARM_THRESHOLD_GENERATOR
TAB_CONFIG
TAB_EVENTI_GUI
TAB_HELP
TAB_INFO_CONFIG
TAB_KIT_CONTATORI
TAB_LISTA_REPORT
TAB_LISTA_VALORI
TAB_LISTA_VALORI_SOST
TAB_LIST_ANALISI
TAB_LIST_EXCEPTION
TAB_LIST_RELATION
TAB_LIST_RESTRICTION
TAB_LIST_RESTRICTION_OB
TAB_LIST_SCRIPT
TAB_REPORT
TAB_RESTRIZIONI_AGGREGATE
TAB_SCRIPTS
TAB_SCRIPT_TEXT
TAB_SCRIPT_VAR1
TAB_SCRIPT_VAR2
TAB_TYPE_ANALISI
TAB_TYPE_CONTATORI
TSTS_FUNCTION_LIB

SELECT  TABLE_SCHEMA,TABLE_NAME 
	FROM information_schema.`TABLES` 
	where table_schema='adams_asp';
SELECT  TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME 
	FROM information_schema.`COLUMNS` 
	where table_schema='adams_asp' and 
	TABLE_NAME='TAB_ALARM_GENERATOR';

SELECT CDR_USE_PLUGIN, CDR_PLUGIN_NAME, CDR_REC_LEN, CDR_FLAG_USE_PATH, CDR_SPECIFY_PL_PATH, TIPO_DI_CONFIGURAZIONE, GLB_DEFAULT_PATH_PL, AUTHOR, LAST_MODIFICATION_TIME, BOUNDARY, LOCK_TABLE, FILE_NAME_CONF, CONF_DEFAULT, ID_INDICE 
FROM adams_asp.TAB_INFO_CONFIG where TIPO_DI_CONFIGURAZIONE = 'N.T.M.-Voce-Standard';