update T_CONFIG_NTM set LISTA_RELAZIONI=TAB_RELAZIONI_ELEMENTO(

TAB_RELAZ_E('155::108',
	TAB_LISTA_ANALISI(TAB_LISANAL(22)),
	TAB_RESTRIZIONI(),
	TAB_RESTRIZIONI_OBB(TAB_RESTRIZIONI_O(169)),
	42,
	-1,
	1,
	-1),
TAB_RELAZ_E('155::109',
	TAB_LISTA_ANALISI(TAB_LISANAL(22)),
	TAB_RESTRIZIONI(),
	TAB_RESTRIZIONI_OBB(TAB_RESTRIZIONI_O(169)),
	42,
	-1,
	1,
	-1)) 
	
where TIPO_DI_CONFIGURAZIONE='N.T.M.-Voce-Standard' and POSIZIONE_ELEMENTO=155