/*
 * SSM_JF_LoggerRow.java
 *
 * Created on 3 maggio 2005, 15.50
 */

/**
 *
 * @author  root
 */
import java.awt.*;
import net.etech.*;
import net.etech.ASP.*;
import net.etech.MDM.*;

public class SSM_JF_LoggerRow extends javax.swing.JPanel {

    /** Creates new form SSM_JF_LoggerRow */
    private CS_BLOCK_LOG Local_msg;
    public SSM_JF_LoggerRow(boolean flagRow,CS_BLOCK_LOG msg) {
        initComponents();
        if(flagRow==false)
        {
            String strMsg=new String(msg.msg).trim();
        
            if(strMsg.indexOf("NOT DEFINED")!=-1)
            {
                jTextField1.setForeground(new java.awt.Color(9,126,165));
            }
        }
        jTextField1.setDocument(new SSM_JTextFieldFilter(SSM_JTextFieldFilter.ALLCHAR,131));
        
        this.Local_msg=msg;
        jTextField1.setCursor(cursor_hand);
        if(flagRow==false)
        {
            this.remove(jLabel1);
            this.remove(jLabel2);
            this.remove(jLabel3);
            this.remove(jLabel4);
            this.remove(jLabel5);
            this.remove(jPanel3);
            this.remove(jLabel8);
            initRow(msg);
            
        }else
        {
            this.remove(jLabel6);
            this.remove(jLabel7);
            this.remove(jTextField1);
            this.remove(jPanel1);
            this.remove(jPanel2);
            this.remove(jButton3);
            
        }
        jButton3.setCursor(cursor_hand);
        jRadioButton1.setCursor(cursor_hand);
        jRadioButton2.setCursor(cursor_hand);
        jRadioButton3.setCursor(cursor_hand);
        jRadioButton4.setCursor(cursor_hand);
        jRadioButton5.setCursor(cursor_hand);
        
    }
    public CS_BLOCK_LOG getMsgBlock()
    {
        return (CS_BLOCK_LOG) Local_msg;
    }
    
    private void initRow(CS_BLOCK_LOG msg)
    {
         jLabel6.setText(""+msg.block);  
         jLabel7.setText(""+msg.cod_err);  
         jTextField1.setText(new String(msg.msg).trim()); 
         switch(msg.urgenza)
         {
             case 0:
                    jRadioButton1.setSelected(true);
                 break;
             case 1:
                    jRadioButton2.setSelected(true);
                 break;
             case 2:
                    jRadioButton3.setSelected(true);
                 break;
         }
         
         switch(msg.priorita)
         {
             case 0:
                    jRadioButton4.setSelected(true);
                 break;
             case 1:
                    jRadioButton5.setSelected(true);
                 break;
         }
    }
    
    public String getMsg()
    {   
        return jTextField1.getText();
    }
    
    public int getAttention()
    {   
       int flag=-1;
       if(jRadioButton1.isSelected()==true)
       { 
           return flag=0;
       }else if(jRadioButton2.isSelected()==true)
       {
           return flag=1;
       }
       else if(jRadioButton3.isSelected()==true)
       {
           return flag=2;
       }
       return flag;
    }
    
    public int getPriority()
    {   
       int flag=-1;
       if(jRadioButton4.isSelected()==true)
       { 
           return flag=0;
       }else if(jRadioButton5.isSelected()==true)
       {
           return flag=1;
       }
        return flag;
    }
    
    public void setColor(Color c)
    {
        jTextField1.setForeground(c);
    }

    public void disableAll()
    {
           jButton3.setEnabled(false);
           jTextField1.setEditable(false);
           jRadioButton1.setEnabled(false);
           jRadioButton2.setEnabled(false);
           jRadioButton3.setEnabled(false);
           jRadioButton4.setEnabled(false);
           jRadioButton5.setEnabled(false);
    }
    
    public void setMsg(String msg)
    {   
        jTextField1.setText(msg);
    }
    
    public void setAttention(int i)
    {   
       
       if(i==0)
       { 
           jRadioButton1.setSelected(true);
       }else if(i==1)
       {
           jRadioButton2.setSelected(true);
       }else if(i==2)
       {
           jRadioButton3.setSelected(true);
       }
       
    }
    
    public void setPriority(int i)
    {   
       if(i==0)
       { 
           jRadioButton4.setSelected(true);
       }else if(i==1)
       {
           jRadioButton5.setSelected(true);
       }
    }
            
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
          buttonGroup1 = new javax.swing.ButtonGroup();
          buttonGroup2 = new javax.swing.ButtonGroup();
          jLabel1 = new javax.swing.JLabel();
          jLabel2 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          jLabel4 = new javax.swing.JLabel();
          jLabel5 = new javax.swing.JLabel();
          jLabel6 = new javax.swing.JLabel();
          jLabel7 = new javax.swing.JLabel();
          jTextField1 = new javax.swing.JTextField();
          jPanel1 = new javax.swing.JPanel();
          jRadioButton1 = new javax.swing.JRadioButton();
          jRadioButton2 = new javax.swing.JRadioButton();
          jRadioButton3 = new javax.swing.JRadioButton();
          jPanel2 = new javax.swing.JPanel();
          jRadioButton4 = new javax.swing.JRadioButton();
          jRadioButton5 = new javax.swing.JRadioButton();
          jPanel3 = new javax.swing.JPanel();
          jLabel8 = new javax.swing.JLabel();
          jButton3 = new javax.swing.JButton();
          
          
          setLayout(new java.awt.GridBagLayout());
          java.awt.GridBagConstraints gridBagConstraints1;
          
          setBackground(new java.awt.Color(230, 230, 230));
          setMaximumSize(new java.awt.Dimension(870, 25));
          setMinimumSize(new java.awt.Dimension(870, 25));
          setPreferredSize(new java.awt.Dimension(870, 25));
          jLabel1.setBackground(new java.awt.Color(9, 126, 165));
          jLabel1.setFont(new java.awt.Font("Dialog", 0, 10));
          jLabel1.setForeground(java.awt.Color.white);
          jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
          jLabel1.setText("Block");
          jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
          jLabel1.setMaximumSize(new java.awt.Dimension(40, 20));
          jLabel1.setMinimumSize(new java.awt.Dimension(40, 20));
          jLabel1.setPreferredSize(new java.awt.Dimension(40, 20));
          jLabel1.setOpaque(true);
          gridBagConstraints1 = new java.awt.GridBagConstraints();
          gridBagConstraints1.gridx = 1;
          gridBagConstraints1.gridy = 0;
          gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
          add(jLabel1, gridBagConstraints1);
          
          jLabel2.setBackground(new java.awt.Color(9, 126, 165));
          jLabel2.setFont(new java.awt.Font("Dialog", 0, 10));
          jLabel2.setForeground(java.awt.Color.white);
          jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
          jLabel2.setText("Error");
          jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
          jLabel2.setMaximumSize(new java.awt.Dimension(30, 20));
          jLabel2.setMinimumSize(new java.awt.Dimension(30, 20));
          jLabel2.setPreferredSize(new java.awt.Dimension(30, 20));
          jLabel2.setOpaque(true);
          gridBagConstraints1 = new java.awt.GridBagConstraints();
          gridBagConstraints1.gridx = 2;
          gridBagConstraints1.gridy = 0;
          gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
          add(jLabel2, gridBagConstraints1);
          
          jLabel3.setBackground(new java.awt.Color(9, 126, 165));
          jLabel3.setForeground(java.awt.Color.white);
          jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
          jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/message.png")));
          jLabel3.setText("Message");
          jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
          jLabel3.setMaximumSize(new java.awt.Dimension(400, 20));
          jLabel3.setMinimumSize(new java.awt.Dimension(400, 20));
          jLabel3.setPreferredSize(new java.awt.Dimension(400, 20));
          jLabel3.setOpaque(true);
          gridBagConstraints1 = new java.awt.GridBagConstraints();
          gridBagConstraints1.gridx = 3;
          gridBagConstraints1.gridy = 0;
          gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
          add(jLabel3, gridBagConstraints1);
          
          jLabel4.setBackground(new java.awt.Color(9, 126, 165));
          jLabel4.setForeground(java.awt.Color.white);
          jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
          jLabel4.setText("Attention");
          jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
          jLabel4.setMaximumSize(new java.awt.Dimension(180, 20));
          jLabel4.setMinimumSize(new java.awt.Dimension(180, 20));
          jLabel4.setPreferredSize(new java.awt.Dimension(180, 20));
          jLabel4.setOpaque(true);
          gridBagConstraints1 = new java.awt.GridBagConstraints();
          gridBagConstraints1.gridx = 4;
          gridBagConstraints1.gridy = 0;
          gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
          add(jLabel4, gridBagConstraints1);
          
          jLabel5.setBackground(new java.awt.Color(9, 126, 165));
          jLabel5.setForeground(java.awt.Color.white);
          jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
          jLabel5.setText("Priority");
          jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
          jLabel5.setMaximumSize(new java.awt.Dimension(140, 20));
          jLabel5.setMinimumSize(new java.awt.Dimension(140, 20));
          jLabel5.setPreferredSize(new java.awt.Dimension(140, 20));
          jLabel5.setOpaque(true);
          gridBagConstraints1 = new java.awt.GridBagConstraints();
          gridBagConstraints1.gridx = 5;
          gridBagConstraints1.gridy = 0;
          gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
          add(jLabel5, gridBagConstraints1);
          
          jLabel6.setBackground(new java.awt.Color(230, 230, 230));
          jLabel6.setFont(new java.awt.Font("Dialog", 0, 11));
          jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
          jLabel6.setText("48");
          jLabel6.setToolTipText("Identificativo del blocco");
          jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
          jLabel6.setMaximumSize(new java.awt.Dimension(40, 20));
          jLabel6.setMinimumSize(new java.awt.Dimension(40, 20));
          jLabel6.setPreferredSize(new java.awt.Dimension(40, 20));
          gridBagConstraints1 = new java.awt.GridBagConstraints();
          gridBagConstraints1.gridx = 1;
          gridBagConstraints1.gridy = 1;
          gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
          gridBagConstraints1.insets = new java.awt.Insets(1, 1, 1, 1);
          add(jLabel6, gridBagConstraints1);
          
          jLabel7.setBackground(new java.awt.Color(230, 230, 230));
          jLabel7.setFont(new java.awt.Font("Dialog", 0, 11));
          jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
          jLabel7.setText("01");
          jLabel7.setToolTipText("Identificativo dell'errore");
          jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
          jLabel7.setMaximumSize(new java.awt.Dimension(30, 20));
          jLabel7.setMinimumSize(new java.awt.Dimension(30, 20));
          jLabel7.setPreferredSize(new java.awt.Dimension(30, 20));
          gridBagConstraints1 = new java.awt.GridBagConstraints();
          gridBagConstraints1.gridx = 2;
          gridBagConstraints1.gridy = 1;
          gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
          gridBagConstraints1.insets = new java.awt.Insets(1, 1, 1, 1);
          add(jLabel7, gridBagConstraints1);
          
          jTextField1.setFont(new java.awt.Font("Dialog", 0, 11));
          jTextField1.setText("Messaggio di errore");
          jTextField1.setMaximumSize(new java.awt.Dimension(400, 20));
          jTextField1.setMinimumSize(new java.awt.Dimension(400, 20));
          jTextField1.setPreferredSize(new java.awt.Dimension(400, 20));
          jTextField1.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  jTextField1ActionPerformed(evt);
              }
          });
          
          gridBagConstraints1 = new java.awt.GridBagConstraints();
          gridBagConstraints1.gridx = 3;
          gridBagConstraints1.gridy = 1;
          gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
          gridBagConstraints1.insets = new java.awt.Insets(1, 1, 1, 1);
          add(jTextField1, gridBagConstraints1);
          
          jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));
          
          jPanel1.setBackground(new java.awt.Color(230, 230, 230));
          jPanel1.setMaximumSize(new java.awt.Dimension(180, 20));
          jPanel1.setMinimumSize(new java.awt.Dimension(180, 20));
          jPanel1.setPreferredSize(new java.awt.Dimension(180, 20));
          jRadioButton1.setBackground(new java.awt.Color(230, 230, 230));
          jRadioButton1.setFont(new java.awt.Font("Dialog", 0, 11));
          jRadioButton1.setText("Low");
          buttonGroup1.add(jRadioButton1);
          jRadioButton1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_off_mini.gif")));
          jRadioButton1.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_on_mini.gif")));
          jRadioButton1.setFocusPainted(false);
          jRadioButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_off_mini.gif")));
          jRadioButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_on_over_mini.gif")));
          jRadioButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_off_over_mini.gif")));
          jRadioButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_on_over_mini.gif")));
          jRadioButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_on_mini.gif")));
          jPanel1.add(jRadioButton1);
          
          jRadioButton2.setBackground(new java.awt.Color(230, 230, 230));
          jRadioButton2.setFont(new java.awt.Font("Dialog", 0, 11));
          jRadioButton2.setText("Medium");
          buttonGroup1.add(jRadioButton2);
          jRadioButton2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_off_mini.gif")));
          jRadioButton2.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_on_mini.gif")));
          jRadioButton2.setFocusPainted(false);
          jRadioButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_off_mini.gif")));
          jRadioButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_on_over_mini.gif")));
          jRadioButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_off_over_mini.gif")));
          jRadioButton2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_on_over_mini.gif")));
          jRadioButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_on_mini.gif")));
          jPanel1.add(jRadioButton2);
          
          jRadioButton3.setBackground(new java.awt.Color(230, 230, 230));
          jRadioButton3.setFont(new java.awt.Font("Dialog", 0, 11));
          jRadioButton3.setText("High");
          buttonGroup1.add(jRadioButton3);
          jRadioButton3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_off_mini.gif")));
          jRadioButton3.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_on_mini.gif")));
          jRadioButton3.setFocusPainted(false);
          jRadioButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_off_mini.gif")));
          jRadioButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_on_over_mini.gif")));
          jRadioButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_off_over_mini.gif")));
          jRadioButton3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_on_over_mini.gif")));
          jRadioButton3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_on_mini.gif")));
          jPanel1.add(jRadioButton3);
          
          gridBagConstraints1 = new java.awt.GridBagConstraints();
          gridBagConstraints1.gridx = 4;
          gridBagConstraints1.gridy = 1;
          gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
          gridBagConstraints1.insets = new java.awt.Insets(1, 1, 1, 1);
          add(jPanel1, gridBagConstraints1);
          
          jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));
          
          jPanel2.setBackground(new java.awt.Color(230, 230, 230));
          jPanel2.setMaximumSize(new java.awt.Dimension(140, 20));
          jPanel2.setMinimumSize(new java.awt.Dimension(140, 20));
          jPanel2.setPreferredSize(new java.awt.Dimension(140, 20));
          jRadioButton4.setBackground(new java.awt.Color(230, 230, 230));
          jRadioButton4.setFont(new java.awt.Font("Dialog", 0, 11));
          jRadioButton4.setText("Low");
          buttonGroup2.add(jRadioButton4);
          jRadioButton4.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_off_mini.gif")));
          jRadioButton4.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_on_mini.gif")));
          jRadioButton4.setFocusPainted(false);
          jRadioButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_off_mini.gif")));
          jRadioButton4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_on_over_mini.gif")));
          jRadioButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_off_over_mini.gif")));
          jRadioButton4.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_on_over_mini.gif")));
          jRadioButton4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_on_mini.gif")));
          jPanel2.add(jRadioButton4);
          
          jRadioButton5.setBackground(new java.awt.Color(230, 230, 230));
          jRadioButton5.setFont(new java.awt.Font("Dialog", 0, 11));
          jRadioButton5.setText("High");
          buttonGroup2.add(jRadioButton5);
          jRadioButton5.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_off_mini.gif")));
          jRadioButton5.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_on_mini.gif")));
          jRadioButton5.setFocusPainted(false);
          jRadioButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_off_mini.gif")));
          jRadioButton5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_on_over_mini.gif")));
          jRadioButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_off_over_mini.gif")));
          jRadioButton5.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_on_over_mini.gif")));
          jRadioButton5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_on_mini.gif")));
          jPanel2.add(jRadioButton5);
          
          gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 5;
        gridBagConstraints1.gridy = 1;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.insets = new java.awt.Insets(1, 1, 1, 1);
        add(jPanel2, gridBagConstraints1);
        
        jPanel3.setBackground(new java.awt.Color(230, 230, 230));
        jPanel3.setMaximumSize(new java.awt.Dimension(22, 20));
        jPanel3.setMinimumSize(new java.awt.Dimension(22, 20));
        jPanel3.setPreferredSize(new java.awt.Dimension(22, 20));
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 6;
        gridBagConstraints1.gridy = 0;
        add(jPanel3, gridBagConstraints1);
        
        jLabel8.setBackground(new java.awt.Color(9, 126, 167));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel8.setMaximumSize(new java.awt.Dimension(50, 20));
        jLabel8.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel8.setPreferredSize(new java.awt.Dimension(50, 20));
        jLabel8.setOpaque(true);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 0;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        add(jLabel8, gridBagConstraints1);
        
        jButton3.setBackground(new java.awt.Color(230, 230, 230));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b_reset.jpg")));
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b_reset_press.jpg")));
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b_reset_over.jpg")));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 1;
        add(jButton3, gridBagConstraints1);
        
    }//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Add your handling code here:
        jTextField1.setText("NOT DEFINED");
        jTextField1.setForeground(new java.awt.Color(9,126,165));
        jRadioButton1.setSelected(true);
        jRadioButton4.setSelected(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
    private java.awt.Cursor cursor_hand         = new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR);
    private java.awt.Cursor cursor_wait         = new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR);
    private java.awt.Cursor cursor_default      = new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR);
}
