
import java.awt.Toolkit;
import java.awt.Dimension;

/**
 * <p align="center"><font size="1"><b><font size="3" face="Times New Roman, Times, serif"> MONITOR CLIENT</font></b></font></p>
 * <p align="center"> <b>Author:</b></p>
 * <p align="center">-  Raffaele Ficcadenti (E-TECH) Created on 13/05/2005 - <a href="mailto:raffaele.ficcadenti@e-tech.net">raffaele.ficcadenti@e-tech.net</a></p>
 *
 * Questa classe è una ridefinizione dell'oggetto JDialog, viene utilizzata per presentare all'utente la scelta della centrale
 * sulla quale verrà modificato il file di log. La finestra che viene presentata all'utente presenta una lista di RadioButton 
 * sensibili e selezionabili opportunamente dall'utente.
 */
public class SSM_JD_SelectBlock extends javax.swing.JDialog {

    /** Creates new form SSM_JD_SelectBlock */
    private java.awt.Cursor cursor_hand         = new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR);
    private java.awt.Cursor cursor_wait         = new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR);
    private java.awt.Cursor cursor_default      = new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR);
    private SSM_JF_ConfigLog parente             = null;
    
    public SSM_JD_SelectBlock(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jRadioButton3.setCursor(cursor_hand);
        jRadioButton4.setCursor(cursor_hand);
        
        jButton1.setCursor(cursor_hand);
        jButton2.setCursor(cursor_hand);
        
        jLabel1.setFont(SSM_GlobalParam.font_B12);
        jRadioButton3.setSelected(true);
        
        setCenteredFrame(300,200);
    }
    
    public void disableOpt2()
    {
        jRadioButton4.setEnabled(false);
    }
    
    public void setLabel(String str)
    {
        jLabel1.setText(str);
    }
    
    public void setOptions(String str1,String str2)
    {
        jRadioButton3.setText(str1);
        jRadioButton4.setText(str2);
    }
    
    public void setParente(SSM_JF_ConfigLog p)
    {
       parente=p;
       parente.opt1=1;
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
          buttonGroup1 = new javax.swing.ButtonGroup();
          jPanel1 = new javax.swing.JPanel();
          jLabel1 = new javax.swing.JLabel();
          jRadioButton3 = new javax.swing.JRadioButton();
          jRadioButton4 = new javax.swing.JRadioButton();
          jPanel3 = new javax.swing.JPanel();
          jButton1 = new javax.swing.JButton();
          jButton2 = new javax.swing.JButton();
          
          
          setModal(true);
          addWindowListener(new java.awt.event.WindowAdapter() {
              public void windowClosing(java.awt.event.WindowEvent evt) {
                  closeDialog(evt);
              }
          });
          
          jPanel1.setLayout(new java.awt.GridLayout(0, 1));
          
          jPanel1.setBackground(new java.awt.Color(230, 230, 230));
          jPanel1.setBorder(new javax.swing.border.EtchedBorder());
          jLabel1.setBackground(new java.awt.Color(230, 230, 230));
          jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
          jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help.png")));
          jLabel1.setText("jLabel1");
          jLabel1.setOpaque(true);
          jPanel1.add(jLabel1);
          
          jRadioButton3.setBackground(new java.awt.Color(230, 230, 230));
          jRadioButton3.setFont(new java.awt.Font("Dialog", 0, 11));
          jRadioButton3.setText("Medium");
          buttonGroup1.add(jRadioButton3);
          jRadioButton3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_off.gif")));
          jRadioButton3.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_on.gif")));
          jRadioButton3.setFocusPainted(false);
          jRadioButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
          jRadioButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_off.gif")));
          jRadioButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_on_over.gif")));
          jRadioButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_off_over.gif")));
          jRadioButton3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_on_over.gif")));
          jRadioButton3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_on.gif")));
          jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  jRadioButton3ActionPerformed(evt);
              }
          });
          
          jPanel1.add(jRadioButton3);
          
          jRadioButton4.setBackground(new java.awt.Color(230, 230, 230));
          jRadioButton4.setFont(new java.awt.Font("Dialog", 0, 11));
          jRadioButton4.setText("Medium");
          buttonGroup1.add(jRadioButton4);
          jRadioButton4.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_off.gif")));
          jRadioButton4.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_on.gif")));
          jRadioButton4.setFocusPainted(false);
          jRadioButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
          jRadioButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_off.gif")));
          jRadioButton4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_on_over.gif")));
          jRadioButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_off_over.gif")));
          jRadioButton4.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_on_over.gif")));
          jRadioButton4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_on.gif")));
          jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  jRadioButton4ActionPerformed(evt);
              }
          });
          
          jPanel1.add(jRadioButton4);
          
          jPanel3.setBackground(new java.awt.Color(230, 230, 230));
            jButton1.setBackground(new java.awt.Color(230, 230, 230));
            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/apply.jpg")));
            jButton1.setBorder(null);
            jButton1.setBorderPainted(false);
            jButton1.setContentAreaFilled(false);
            jButton1.setFocusPainted(false);
            jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/apply_press.jpg")));
            jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/apply_over.jpg")));
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });
            
            jPanel3.add(jButton1);
            
            jButton2.setForeground(java.awt.Color.red);
            jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.jpg")));
            jButton2.setBorderPainted(false);
            jButton2.setContentAreaFilled(false);
            jButton2.setFocusPainted(false);
            jButton2.setMaximumSize(new java.awt.Dimension(50, 20));
            jButton2.setMinimumSize(new java.awt.Dimension(50, 20));
            jButton2.setPreferredSize(new java.awt.Dimension(50, 20));
            jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_press.jpg")));
            jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_over.jpg")));
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });
            
            jPanel3.add(jButton2);
            
            jPanel1.add(jPanel3);
          
          getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        
        pack();
    }//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Add your handling code here:
        closeFrame();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // Add your handling code here:
        parente.opt1=2;
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // Add your handling code here:
        parente.opt1=1;
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Add your handling code here:
        parente.opt1=-1;
        closeFrame();
    }//GEN-LAST:event_jButton2ActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        closeFrame();
    }//GEN-LAST:event_closeDialog

    
    private void closeFrame()
    {
        setVisible(false);
        this.dispose();
    }
    
    private void setCenteredFrame(int width,int height)
    {
        java.awt.Toolkit kit = Toolkit.getDefaultToolkit();
        Dimension screenSize = kit.getScreenSize();
        int screenWCenter = screenSize.width/2;
        int screenHCenter = screenSize.height/2;

        this.setSize(width,height);
        this.setLocation(screenWCenter-(width/2),screenHCenter-(height/2));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables

}
