##
##	ADAMS build environment
##

include $(ADAMS_HOME)/make/configure.mk

##
## General settings

MAKEFLAGS=--no-keep-going --no-print-directory
export MAKEFLAGS

ifeq ($(ADAMS_OPSYS), HPUX)

ADAMS_PLATFORM = ADAMS_HPUX

endif

ifeq ($(ADAMS_OPSYS), LINUX)

ADAMS_PLATFORM = ADAMS_LINUX

endif

# Build paths

ADAMS_INCLUDE_PATH   = $(ADAMS_HOME)/include
ADAMS_LIB_PATH       = $(ADAMS_HOME)/$(ADAMS_LIBDIR_NAME)
ADAMS_3RDPARTY_PATH  = $(ADAMS_HOME)/3rdparty
ADAMS_SHARED_PATH    = $(ADAMS_HOME)/share
ADAMS_IDL_PATH       = $(ADAMS_HOME)/idl
ADAMS_XML_PATH       = $(ADAMS_HOME)/xml
ADAMS_BUILD_INSTALL  = $(ADAMS_HOME)/install
ADAMS_MAKE_PATH      = $(ADAMS_HOME)/make
ADAMS_WEB_INSTALL    = $(ADAMS_BUILD_INSTALL)/bep/portal
ADAMS_INSTALL_LIB_NAME = $(ADAMS_LIBDIR_NAME)
ADAMS_INSTALL_JAR_PACKAGES_DIR = packages

# Runtime paths
ADAMS_RUNTIME_LIB_PATH = $(ADAMS_PREFIX)/$(ADAMS_LIBDIR_NAME)
ADAMS_RUNTIME_BIN_PATH = $(ADAMS_PREFIX)/bin
ADAMS_RUNTIME_SHARED_PATH = $(ADAMS_PREFIX)/share/adams

# ...

ADAMS_INCLUDE  = -I$(ADAMS_INCLUDE_PATH)
ADAMS_LIB      = -L$(ADAMS_LIB_PATH) -L$(ADAMS_BUILD_INSTALL)/$(ADAMS_LIBDIR_NAME)

# Build install is make inside source dir instead than in ADAMS_PREFIX path that is
# real world installation path
CMAKE_INSTALL_PREFIX=$(ADAMS_BUILD_INSTALL)
export CMAKE_INSTALL_PREFIX

##
## C/C++ settings
##

ifeq ($(ADAMS_PLATFORM), ADAMS_HPUX)
ADAMS_SHAREDLIBCMD=-Wl,+b,
ADAMS_SHAREDLIBSEARCH=$(ADAMS_SHAREDLIBCMD)$(ADAMS_RUNTIME_LIB_PATH)
ADAMS_CFLAGS = -D$(ADAMS_PLATFORM) -mlp64 -pthread $(ADAMS_SHAREDLIBSEARCH) $(ADAMS_THREAD_CFLAGS)
ADAMS_SYSLIBS = -lm -lrt

# Conditional CXXFLAGS depending on used compiler (g++/aCC)
ifeq ($(CXX), g++)
ADAMS_GCC_VERSION=4.3.2
ADAMS_CXXFLAGS  = $(ADAMS_CFLAGS) -Wno-deprecated
ADAMS_SHFLAGS =
ADAMS_SHAREDLIBLINK=-shared
ADAMS_C_SHAREDLIBLINK=-shared
ADAMS_CXX_VENDOR_INCLUDE=/usr/include/c++/$(ADAMS_GCC_VERSION)
else
ADAMS_CXXFLAGS = -D$(ADAMS_PLATFORM) +DD64 +DSnative -AA +e -w -D__STRICT_ANSI__ -D_HPUX_SOURCE -Wl,+b,$(ADAMS_RUNTIME_LIB_PATH) $(ADAMS_THREAD_CFLAGS_CXX)
ADAMS_SHFLAGS =
ADAMS_SHAREDLIBLINK=-b
ADAMS_C_SHAREDLIBLINK=-shared
ADAMS_CXX_VENDOR_INCLUDE=/usr/include/aCC
endif
endif

ifeq ($(ADAMS_PLATFORM), ADAMS_LINUX)
ADAMS_SHAREDLIBCMD=-Wl,-rpath=
ADAMS_SHAREDLIBSEARCH=$(ADAMS_SHAREDLIBCMD)$(ADAMS_RUNTIME_LIB_PATH)
ADAMS_CFLAGS += $(ADAMS_SHAREDLIBSEARCH) $(ADAMS_THREAD_CFLAGS)
ADAMS_DEFINE += -D$(ADAMS_PLATFORM) -D_GNU_SOURCE -pthread
ADAMS_SYSLIBS = -lm -ldl

ADAMS_GCC_VERSION=4.5
ADAMS_CXXFLAGS  += $(ADAMS_CFLAGS) -Wno-deprecated
ADAMS_SHFLAGS = -fPIC
ADAMS_SHAREDLIBLINK=-shared
ADAMS_C_SHAREDLIBLINK=-shared
ADAMS_OPTIMIZE_CFLAGS_RELEASE = -O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables
ADAMS_OPTIMIZE_CFLAGS_DEBUG = -g
# ADAMS_CXX_VENDOR_INCLUDE=$ADAMS_TK_DIR/include/c++/$(ADAMS_GCC_VERSION)
endif

ifeq ($(ADAMS_MODE), PRODUCTION)
CMAKE_BUILD_TYPE_VAR=Release
ADAMS_DEFINE += -DPRODUCTION
ADAMS_OPTIMIZE_CFLAGS = $(ADAMS_OPTIMIZE_CFLAGS_RELEASE)
else
CMAKE_BUILD_TYPE_VAR=Debug
ADAMS_DEFINE += -DTEST_PLAN
ADAMS_OPTIMIZE_CFLAGS = $(ADAMS_OPTIMIZE_CFLAGS_DEBUG)
endif

##
## Database settings
##

ADAMS_DB_TYPE = MySQL
ADAMS_JAVA_DB_DRIVER_CANONICAL_NAME = adams_java_db_driver.jar

ifeq ($(ADAMS_DB_TYPE), MySQL)
ADAMS_JAVA_DB_DRIVER_VERSION = 5.1.22
ADAMS_DB_DRIVER_PATH=${ADAMS_3RDPARTY_PATH}/mysql-connector-java
ADAMS_JAVA_DB_DRIVER = mysql-connector-java-${ADAMS_JAVA_DB_DRIVER_VERSION}-bin.jar
ADAMS_JAVA_DB_DRIVER_LIB = $(ADAMS_DB_DRIVER_PATH)/$(ADAMS_JAVA_DB_DRIVER)
endif

##
## Java Settings
##

ifeq ($(USE_NATIVE_JACORB), no)

SLF4J_VERSION=1.6.4
ADAMS_JAVAIDL = $(ADAMS_HOME)/3rdparty/jacorb/jacorb-$(ADAMS_JACORB_VERSION)/bin/idl
ADAMS_JAVA_ORB_LIB = $(ADAMS_HOME)/3rdparty/jacorb/jacorb-$(ADAMS_JACORB_VERSION)/lib/jacorb.jar
ADAMS_JAVA_SLF4J_LIB = $(ADAMS_HOME)/3rdparty/jacorb/jacorb-$(ADAMS_JACORB_VERSION)/lib/slf4j-api-$(SLF4J_VERSION).jar

else

ADAMS_JAVAIDL = idl
ADAMS_JAVA_ORB_LIB =

endif

ADAMS_CLASSPATH = .:$(CLASSDIR)
CLASSPATH = $(ADAMS_CLASSPATH)
ADAMS_JARSIGNER=$(JAVA_HOME)/bin/jarsigner
export ADAMS_JARSIGNER

##
## CORBA Settings
##

ifeq ($(ADAMS_PLATFORM), ADAMS_LINUX)

ADAMS_TAO_BASE		= /usr
ADAMS_TAO_ROOT		= $(ADAMS_TAO_BASE)
ADAMS_TAO_BINDIR	= $(ADAMS_TAO_ROOT)/bin
ADAMS_TAO_LIBDIR	= $(ADAMS_TAO_ROOT)/lib64/
ADAMS_TAO_INCDIR	= $(ADAMS_TAO_ROOT)/include
ADAMS_TAO_INCLUDE	= -I$(ADAMS_TAO_INCDIR)

endif

ADAMS_CORBA_DEFINES=-DP_USE_TAO -DP_USE_POSIX_THREADS
ifeq ($(HAS_ACE_VERSIONED_NAMESPACE), yes)
ADAMS_CORBA_DEFINES +=-DACE_HAS_VERSIONED_NAMESPACE=1
endif
ADAMS_CORBA_CFLAGS=

ADAMS_LFLAGS = $(ADAMS_THREAD_LFLAGS) $(ADAMS_LIB_PATH) -L$(ADAMS_TAO_LIBDIR) $(ADAMS_SHAREDLIBCMD)$(ADAMS_RUNTIME_LIB_PATH) -lm -lrt
ADAMS_CXXFLAGS += $(ADAMS_CORBA_CFLAGS)
ADAMS_DEFINE += $(ADAMS_CORBA_DEFINES)
#ADAMS_INCLUDE += $(ADAMS_TAO_INCLUDE)

## export all relevant
##
## !!! be sure to couple exported variables in "build.cmake" !!!

export ADAMS_SHAREDLIBCMD
export ADAMS_SHAREDLIBSEARCH
export ADAMS_CFLAGS
export ADAMS_SYSLIBS
export ADAMS_CXXFLAGS
export ADAMS_SHFLAGS
export ADAMS_SHAREDLIBLINK
export ADAMS_C_SHAREDLIBLINK
export ADAMS_LFLAGS
export ADAMS_DEFINE
export ADAMS_INCLUDE_PATH
export ADAMS_LIB_PATH
export ADAMS_3RDPARTY_PATH
export ADAMS_SHARED_PATH
export ADAMS_INCLUDE
export ADAMS_LIB
export ADAMS_JAVAIDL
export ADAMS_IDL_PATH
export ADAMS_XML_PATH
export ADAMS_JAVA_ORB_LIB
export ADAMS_CLASSPATH
export ADAMS_PLATFORM
export ADAMS_RUNTIME_LIB_PATH
export ADAMS_PREFIX
export ADAMS_BUILD_INSTALL
export ADAMS_WEB_INSTALL
export ADAMS_DB_TYPE
export ADAMS_JAVA_DB_DRIVER_VERSION
export ADAMS_DB_DRIVER_PATH
export ADAMS_JAVA_DB_DRIVER
export ADAMS_JAVA_DB_DRIVER_LIB
export ADAMS_JAVA_DB_DRIVER_CANONICAL_NAME
export ADAMS_TAO_BASE
export ADAMS_TAO_BINDIR
export ADAMS_TAO_LIBDIR
export ADAMS_TAO_INCDIR
export ADAMS_TAO_INCLUDE
export ADAMS_CORBA_CFLAGS
export ADAMS_CORBA_DEFINES
export ADAMS_OPTIMIZE_CFLAGS_RELEASE
export ADAMS_OPTIMIZE_CFLAGS_DEBUG
export CMAKE_BUILD_TYPE_VAR
export ADAMS_INSTALL_LIB_NAME
export ADAMS_RUNTIME_LIB_PATH
export ADAMS_RUNTIME_BIN_PATH
export ADAMS_RUNTIME_SHARED_PATH
export ADAMS_INSTALL_JAR_PACKAGES_DIR

#---
