DROP TABLE RDA_DBA.L_INDEX_LIB CASCADE CONSTRAINTS;

CREATE TABLE RDA_DBA.L_INDEX_LIB
(
  ID_INDICE    NUMBER(2),
  DESC_INDICE  VARCHAR2(40 BYTE),
  NOME_FILE    VARCHAR2(50 BYTE)
)
TABLESPACE TBS_RETE7
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             160K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP PUBLIC SYNONYM L_INDEX_LIB;

CREATE PUBLIC SYNONYM L_INDEX_LIB FOR RDA_DBA.L_INDEX_LIB;


GRANT DELETE, INSERT, SELECT, UPDATE ON RDA_DBA.L_INDEX_LIB TO OPS$CORBA;

GRANT DELETE, INSERT, SELECT, UPDATE ON RDA_DBA.L_INDEX_LIB TO OPS$ORBIX;
