ALTER TABLE OPS$ORBIX.L_LIBRERIA_PLUGIN
 DROP PRIMARY KEY CASCADE;
DROP TABLE OPS$ORBIX.L_LIBRERIA_PLUGIN CASCADE CONSTRAINTS;

CREATE TABLE OPS$ORBIX.L_LIBRERIA_PLUGIN
(
  NOME_PLUGIN             VARCHAR2(30 BYTE),
  TIPO_DI_CONFIGURAZIONE  VARCHAR2(30 BYTE),
  DESCRIZIONE             LONG
)
TABLESPACE TBS_RETE7
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             160K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX OPS$ORBIX.PK_LIBR_PLUGIN ON OPS$ORBIX.L_LIBRERIA_PLUGIN
(NOME_PLUGIN, TIPO_DI_CONFIGURAZIONE)
LOGGING
TABLESPACE TBS_RETE7
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             160K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE OPS$ORBIX.L_LIBRERIA_PLUGIN ADD (
  CONSTRAINT PK_LIBR_PLUGIN
 PRIMARY KEY
 (NOME_PLUGIN, TIPO_DI_CONFIGURAZIONE)
    USING INDEX 
    TABLESPACE TBS_RETE7
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          160K
                NEXT             160K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

GRANT DELETE, INSERT, SELECT, UPDATE ON OPS$ORBIX.L_LIBRERIA_PLUGIN TO RDA_MODIFY_ALL;
