ALTER TABLE OPS$ORBIX.TAB_SCRIPTS
 DROP PRIMARY KEY CASCADE;
DROP TABLE OPS$ORBIX.TAB_SCRIPTS CASCADE CONSTRAINTS;

CREATE TABLE OPS$ORBIX.TAB_SCRIPTS
(
  TIPO_DI_CONFIGURAZIONE  VARCHAR2(30 BYTE)     NOT NULL,
  IDSCRIPT                NUMBER,
  TAG                     VARCHAR2(30 BYTE),
  NUMVARIABLE1            NUMBER,
  NUMVARIABLE2            NUMBER,
  NUMSCRIPTTEXT           NUMBER,
--  VARIABLES1              OPS$ORBIX.TAB_VARIABLE,
--  VARIABLES2              OPS$ORBIX.TAB_VARIABLE,
--  SCRIPTTEXT              OPS$ORBIX.TAB_TEXTSCRIPT,
  RESULTVARNAME           VARCHAR2(30 BYTE),
  RESULTTYPE              NUMBER,
  FLAG_VALIDATE           NUMBER
)
TABLESPACE TBS_RETE7
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             160K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE OPS$ORBIX.TAB_SCRIPTS ADD (
  PRIMARY KEY
 (TIPO_DI_CONFIGURAZIONE, IDSCRIPT, TAG)
    USING INDEX 
    TABLESPACE TBS_RETE7
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          160K
                NEXT             160K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

GRANT DELETE, INSERT, SELECT, UPDATE ON OPS$ORBIX.TAB_SCRIPTS TO RDA_MODIFY_ALL;
