ALTER TABLE OPS$ORBIX.TAB_LIST_RELATION
 DROP PRIMARY KEY CASCADE;
DROP TABLE OPS$ORBIX.TAB_LIST_RELATION CASCADE CONSTRAINTS;

CREATE TABLE OPS$ORBIX.TAB_LIST_RELATION
(
	TIPO_DI_CONFIGURAZIONE    VARCHAR2(30 BYTE)   NOT NULL,
	POSIZIONE_ELEMENTO        NUMBER              NOT NULL,
	RELATION_NAME		  VARCHAR2(256),
--	LISTA_ANALISI		  TAB_LISTA_ANALISI,
--	LISTA_RESTRIZ		  TAB_RESTRIZIONI,
--	LISTA_RESTRIZ_OBBLIGAT	  TAB_RESTRIZIONI_OBB,
	DIREZIONE		  NUMBER,
	HEXOUTPUT		  NUMBER,
	NETWORK			  NUMBER,
	GHOST			  NUMBER
)
TABLESPACE TBS_RETE7
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          320K
            NEXT             160K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE OPS$ORBIX.TAB_LIST_RELATION ADD (
  PRIMARY KEY
 (TIPO_DI_CONFIGURAZIONE, POSIZIONE_ELEMENTO, RELATION_NAME)
    USING INDEX 
    TABLESPACE TBS_RETE7
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          160K
                NEXT             160K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

GRANT DELETE, INSERT, SELECT, UPDATE ON OPS$ORBIX.TAB_LIST_RELATION TO RDA_MODIFY_ALL;