ALTER TABLE OPS$ORBIX.TAB_REPORT
 DROP PRIMARY KEY CASCADE;
DROP TABLE OPS$ORBIX.TAB_REPORT CASCADE CONSTRAINTS;

CREATE TABLE OPS$ORBIX.TAB_REPORT
(
  TIPO_DI_CONFIGURAZIONE       VARCHAR2(30 BYTE),
  IDREPORTSCHEMA               NUMBER,
  IDOBJECT                     NUMBER           NOT NULL,
  TYPE                         NUMBER           NOT NULL,
  SUB_TYPE                     NUMBER           NOT NULL,
  TAG                          VARCHAR2(30 BYTE),
  HTML_VSIZE                   NUMBER,
  HTML_HSIZE                   NUMBER,
  HTML_VALIGN                  NUMBER,
  HTML_HALIGN                  NUMBER,
  HTML_WRAP                    NUMBER,
  HTML_FOREGROUND              NUMBER,
  HTML_FOREGROUND_R            NUMBER,
  HTML_FOREGROUND_G            NUMBER,
  HTML_FOREGROUND_B            NUMBER,
  HTML_BACKGROUND              NUMBER,
  HTML_BACKGROUND_R            NUMBER,
  HTML_BACKGROUND_G            NUMBER,
  HTML_BACKGROUND_B            NUMBER,
  HTML_STYLE                   NUMBER,
  HTML_FONTSIZE                NUMBER,
  HTML_BOLD                    NUMBER,
  HTML_ITALIC                  NUMBER,
  HTML_UNDERLINE               NUMBER,
  OBJECT_TAG                   VARCHAR2(30 BYTE),
  OBJECT_HASBORDER             NUMBER,
  OBJECT_SIMPLEBODY            NUMBER,
  OBJECT_EXCELCSV              NUMBER,
  OBJECT_IDANALISYS            NUMBER,
  OBJECT_USEPLUGIN             NUMBER,
  OBJECT_PLUGINNAME            VARCHAR2(256 BYTE),
  OBJECT_DEFAULT_FOREGROUND_R  NUMBER,
  OBJECT_DEFAULT_FOREGROUND_G  NUMBER,
  OBJECT_DEFAULT_FOREGROUND_B  NUMBER,
  OBJECT_DEFAULT_BACKGROUND_R  NUMBER,
  OBJECT_DEFAULT_BACKGROUND_G  NUMBER,
  OBJECT_DEFAULT_BACKGROUND_B  NUMBER,
  HEADER_USERLABEL             VARCHAR2(41 BYTE),
  HEADER_VALUE                 NUMBER,
  HEADER_USERVALUE             VARCHAR2(81 BYTE),
  HEADER_ISURL                 NUMBER,
  HEADER_LINE                  NUMBER,
  BODY_SOURCE                  NUMBER,
  BODY_IDKEY                   NUMBER,
  BODY_IDCOUNTER               NUMBER,
  BODY_TAGCOUNTER              VARCHAR2(20 BYTE),
  BODY_IDSCRIPT                NUMBER,
  BODY_PLUGIN_TAG              VARCHAR2(30 BYTE),
  BODY_PLUGIN_NAME             VARCHAR2(256 BYTE),
  BODY_USERVALUE               VARCHAR2(81 BYTE),
  BODY_ISURL                   NUMBER,
  BODY_TOTALIZER               NUMBER,
  BODY_LINE                    NUMBER,
  BODY_MAXDECIMALDIGIT         NUMBER,
  TOTALIZER_TRIGGER            NUMBER,
  TOTALIZER_LABEL              VARCHAR2(41 BYTE),
  TOTALIZER_REDRAWHEADER       NUMBER,
  TOTALIZER_BORDERAROUND       NUMBER,
  TOTALIZER_LINE               NUMBER,
  TOTALIZER_USESCRIPT          NUMBER,
  TOTALIZER_IDSCRIPT           NUMBER,
  FOOTER_SOURCE                NUMBER,
  FOOTER_LABEL                 VARCHAR2(41 BYTE),
  FOOTER_USERVALUE             VARCHAR2(81 BYTE),
  FOOTER_ISURL                 NUMBER,
  FOOTER_LINE                  NUMBER,
  POSIZIONE                    NUMBER,
  BODY_REPEATKEY               NUMBER
)
TABLESPACE TBS_RETE7
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          800K
            NEXT             160K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE OPS$ORBIX.TAB_REPORT ADD (
  PRIMARY KEY
 (TIPO_DI_CONFIGURAZIONE, IDREPORTSCHEMA, IDOBJECT)
    USING INDEX 
    TABLESPACE TBS_RETE7
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          320K
                NEXT             160K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

GRANT DELETE, INSERT, SELECT, UPDATE ON OPS$ORBIX.TAB_REPORT TO RDA_MODIFY_ALL;
