ALTER TABLE OPS$ORBIX.TAB_EVENTI_GUI
 DROP PRIMARY KEY CASCADE;
DROP TABLE OPS$ORBIX.TAB_EVENTI_GUI CASCADE CONSTRAINTS;

CREATE TABLE OPS$ORBIX.TAB_EVENTI_GUI
(
  TIPO_DI_CONFIGURAZIONE  VARCHAR2(30 BYTE)     NOT NULL,
  IDEXCEPTION             NUMBER                NOT NULL,
  TAG                     VARCHAR2(30 BYTE),
  DESCRIPTION             VARCHAR2(160 BYTE),
  IDTRIGGERRESTRICTION    NUMBER,
  TRIGGEREDSTATUS         NUMBER,
  TRIGGEREDVALUE          VARCHAR2(26 BYTE),
  ACTION                  NUMBER,
  TARGETVALUE             VARCHAR2(26 BYTE),
  IDAGGREGATEEXCEPTION    NUMBER
)
TABLESPACE TBS_RETE7
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             160K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE OPS$ORBIX.TAB_EVENTI_GUI ADD (
  PRIMARY KEY
 (TIPO_DI_CONFIGURAZIONE, IDEXCEPTION)
    USING INDEX 
    TABLESPACE TBS_RETE7
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          160K
                NEXT             160K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

GRANT DELETE, INSERT, SELECT, UPDATE ON OPS$ORBIX.TAB_EVENTI_GUI TO RDA_MODIFY_ALL;