ALTER TABLE OPS$ORBIX.TAB_TYPE_ANALISI
 DROP PRIMARY KEY CASCADE;
DROP TABLE OPS$ORBIX.TAB_TYPE_ANALISI CASCADE CONSTRAINTS;

CREATE TABLE OPS$ORBIX.TAB_TYPE_ANALISI
(
  TIPO_DI_CONFIGURAZIONE  VARCHAR2(30 BYTE)     NOT NULL,
  IDANALISI               NUMBER,
  NOMEANALISI             VARCHAR2(160 BYTE),
  IDCOUNTERKIT            NUMBER,
  FLAGSORT                CHAR(1 BYTE)          NOT NULL,
  FLAGDATA                CHAR(1 BYTE)          NOT NULL,
  FLAGCENTRALE            CHAR(1 BYTE)          NOT NULL,
  FLAGCUMULAZIONE         CHAR(1 BYTE)          NOT NULL
--  LISTA_REPORT            OPS$ORBIX.TAB_REPORT_ABL
)TABLESPACE TBS_RETE7
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             160K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE OPS$ORBIX.TAB_TYPE_ANALISI ADD (
  PRIMARY KEY
 (TIPO_DI_CONFIGURAZIONE, IDANALISI)
    USING INDEX 
    TABLESPACE TBS_RETE7
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          160K
                NEXT             160K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

GRANT DELETE, INSERT, SELECT, UPDATE ON OPS$ORBIX.TAB_TYPE_ANALISI TO RDA_MODIFY_ALL;