ALTER TABLE OPS$ORBIX.TAB_INFO_CONFIG_NTM
 DROP PRIMARY KEY CASCADE;
DROP TABLE OPS$ORBIX.TAB_INFO_CONFIG_NTM CASCADE CONSTRAINTS;

CREATE TABLE OPS$ORBIX.TAB_INFO_CONFIG_NTM
(
  CDR_USE_PLUGIN          NUMBER,
  CDR_PLUGIN_NAME         VARCHAR2(256 BYTE),
  CDR_REC_LEN             NUMBER,
  CDR_FLAG_USE_PATH       NUMBER,
  CDR_SPECIFY_PL_PATH     VARCHAR2(1536 BYTE),
  TIPO_DI_CONFIGURAZIONE  VARCHAR2(30 BYTE),
  GLB_DEFAULT_PATH_PL     VARCHAR2(1536 BYTE),
  AUTHOR                  VARCHAR2(160 BYTE),
  LAST_MODIFICATION_TIME  VARCHAR2(40 BYTE),
  BOUNDARY                NUMBER,
  LOCK_TABLE              VARCHAR2(40 BYTE),
  FILE_NAME_CONF          VARCHAR2(160 BYTE),
  CONF_DEFAULT            CHAR(1 BYTE),
  ID_INDICE               NUMBER(2)
)
TABLESPACE TBS_RETE7
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             160K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP PUBLIC SYNONYM TAB_INFO_CONFIG_NTM;

CREATE PUBLIC SYNONYM TAB_INFO_CONFIG_NTM FOR OPS$ORBIX.TAB_INFO_CONFIG_NTM;


ALTER TABLE OPS$ORBIX.TAB_INFO_CONFIG_NTM ADD (
  PRIMARY KEY
 (TIPO_DI_CONFIGURAZIONE)
    USING INDEX 
    TABLESPACE TBS_RETE7
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          160K
                NEXT             160K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

GRANT DELETE, INSERT, SELECT, UPDATE ON OPS$ORBIX.TAB_INFO_CONFIG_NTM TO RDA_MODIFY_ALL;