ALTER TABLE OPS$ORBIX.TAB_SCRIPT_VAR1
 DROP PRIMARY KEY CASCADE;
DROP TABLE OPS$ORBIX.TAB_SCRIPT_VAR1 CASCADE CONSTRAINTS;

CREATE TABLE OPS$ORBIX.TAB_SCRIPT_VAR1
(
  TIPO_DI_CONFIGURAZIONE  VARCHAR2(30 BYTE)     NOT NULL,
  IDSCRIPT                NUMBER,
  VRBNAME                 VARCHAR2(30)
)
TABLESPACE TBS_RETE7
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             160K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE OPS$ORBIX.TAB_SCRIPT_VAR1 ADD (
  PRIMARY KEY
 (TIPO_DI_CONFIGURAZIONE, IDSCRIPT, VRBNAME)
    USING INDEX 
    TABLESPACE TBS_RETE7
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          160K
                NEXT             160K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

GRANT DELETE, INSERT, SELECT, UPDATE ON OPS$ORBIX.TAB_SCRIPT_VAR1 TO RDA_MODIFY_ALL;