ALTER TABLE OPS$ORBIX.TAB_TYPE_CONTATORI
 DROP PRIMARY KEY CASCADE;
DROP TABLE OPS$ORBIX.TAB_TYPE_CONTATORI CASCADE CONSTRAINTS;

CREATE TABLE OPS$ORBIX.TAB_TYPE_CONTATORI
(
  TIPO_DI_CONFIGURAZIONE  VARCHAR2(30 BYTE)     NOT NULL,
  IDCOUNTER               NUMBER,
  TRIGGERFIELD 		  NUMBER ,
  TRIGGERVALUE            NUMBER ,
  TRIGGERCOUNTER          NUMBER ,
  COUNTERINDEX            NUMBER ,
  COUNTERTYPE             NUMBER ,
  PERCENTOF               NUMBER ,
  TAG                     VARCHAR2(20) ,
  DESCRIPTION             VARCHAR2(160)
)
TABLESPACE TBS_RETE7
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             160K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE OPS$ORBIX.TAB_TYPE_CONTATORI ADD (
  PRIMARY KEY
 (TIPO_DI_CONFIGURAZIONE, IDCOUNTER, TAG)
    USING INDEX 
    TABLESPACE TBS_RETE7
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          160K
                NEXT             160K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

GRANT DELETE, INSERT, SELECT, UPDATE ON OPS$ORBIX.TAB_TYPE_CONTATORI TO RDA_MODIFY_ALL;