ALTER TABLE OPS$ORBIX.TAB_LISTA_REPORT
 DROP PRIMARY KEY CASCADE;
DROP TABLE OPS$ORBIX.TAB_LISTA_REPORT CASCADE CONSTRAINTS;

CREATE TABLE OPS$ORBIX.TAB_LISTA_REPORT
(
  TIPO_DI_CONFIGURAZIONE  VARCHAR2(30 BYTE)     NOT NULL,
  IDANALISI               NUMBER,
  IDREPORT                NUMBER
)
TABLESPACE TBS_RETE7
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             160K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE OPS$ORBIX.TAB_LISTA_REPORT ADD (
  PRIMARY KEY
 (TIPO_DI_CONFIGURAZIONE, IDANALISI, IDREPORT)
    USING INDEX 
    TABLESPACE TBS_RETE7
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          160K
                NEXT             160K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

GRANT DELETE, INSERT, SELECT, UPDATE ON OPS$ORBIX.TAB_LISTA_REPORT TO RDA_MODIFY_ALL;
