ALTER TABLE OPS$ORBIX.TAB_CONFIG
 DROP PRIMARY KEY CASCADE;
DROP TABLE OPS$ORBIX.TAB_CONFIG CASCADE CONSTRAINTS;

CREATE TABLE OPS$ORBIX.TAB_CONFIG
(
  TIPO_DI_CONFIGURAZIONE    VARCHAR2(30 BYTE)   NOT NULL,
  POSIZIONE_ELEMENTO        NUMBER              NOT NULL,
  POSIZIONE_CAMPO_CDR       NUMBER              NOT NULL,
  TIPO_CAMPO                NUMBER              NOT NULL,
  SIZE_CAMPO_CDR            NUMBER              NOT NULL,
  FLAG_ARRAY                CHAR(1 BYTE)        NOT NULL,
  NUMERO_ELEM_ARRAY         NUMBER              NOT NULL,
  LABEL_CDR_NORMALIZZ       VARCHAR2(30 BYTE)   NOT NULL,
  TIPO_OGGETTO_GUI          NUMBER,
  ICONA                     VARCHAR2(30 BYTE),
  RANGE_VAL                 VARCHAR2(15 BYTE),
  VALORE_DEFAULT            NUMBER,
  RAPPRESENTAZ_ESADECIMALE  CHAR(1 BYTE),
  PRIORITA                  NUMBER,
  OPERATORI_RESTRIZIONE     NUMBER,
  LUNG_ELEMENTO_CHIAVE      NUMBER,
  TAG                       VARCHAR2(30 BYTE),
  DESCRIPTION               VARCHAR2(160 BYTE),
  PLUGIN                    VARCHAR2(256 BYTE),
  PLUGIN_PATH               VARCHAR2(1536 BYTE),
  FLAG_ABILITAZIONE_KEY     CHAR(1 BYTE),
  FLAG_CONTATORE            CHAR(1 BYTE),
  FLAG_RESTRIZIONE          CHAR(1 BYTE),
  FLAG_CONBINAZ_ANALISI     CHAR(1 BYTE),
  DEFAULT_RESTRICTION       CHAR(1 BYTE),
  ALWAYS_SHOW_REPORT        CHAR(1 BYTE),
  LINK_TE                   NUMBER,
  SE_INDICE                 CHAR(1 BYTE),
  VALORE_AGGREGAZIONE       NUMBER,
  LENGTH_VALORE_START       NUMBER,
  SUFF_VALORE_INDICE        VARCHAR2(10 BYTE),
  DATA_INIZIO_INDICE        DATE,
  DATA_FINE_INDICE          DATE,
  VALORE_AGGREGAZIONE_DEF   NUMBER,
  FFENABLED                 CHAR(1 BYTE),
  PLUGIN_GUI                VARCHAR2(256 BYTE)
)
TABLESPACE TBS_RETE7
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          320K
            NEXT             160K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE OPS$ORBIX.TAB_CONFIG ADD (
  PRIMARY KEY
 (TIPO_DI_CONFIGURAZIONE, POSIZIONE_ELEMENTO)
    USING INDEX 
    TABLESPACE TBS_RETE7
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          160K
                NEXT             160K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

GRANT DELETE, INSERT, SELECT, UPDATE ON OPS$ORBIX.TAB_CONFIG TO RDA_MODIFY_ALL;